### ISSUE TITLE
为什么这儿的Geosite.dat的尺寸很大

### ISSUE THREAD

**Issue by csquya** [Loyalsoldier/v2ray-rules-dat#1]
和原版的相比 （geosite.dat或者dlc.dat）, 为什么原版的才500来KB, 这儿却要3M多。

原版的路由里加 geolocation-!cn 或者 geosite:gfw 都不起作用，也不知道为什么。

所以我才想试试看这儿的geosite:geolocation-!cn

**Comment by Loyalsoldier** [comment]
之所以称之为加强版 v2ray 规则文件，是因为 geosite.dat 在原版的基础上增加了很多来自其他项目的域名，增加的域名和规则文件用法，请看 [README 文档](https://github.com/Loyalsoldier/v2ray-rules-dat/blob/master/README.md) 。

`geosite:gfw` 不是 GFWList，不要理解错了，指代的是 data 文件夹里的 [gfw 文件](https://github.com/v2ray/domain-list-community/blob/master/data/gfw) 。

`geosite:geolocation-!cn` 指代的是 data 文件夹里的 [geolocation-!cn 文件](https://github.com/v2ray/domain-list-community/blob/master/data/geolocation-!cn) 。

各个类别里面具体包含什么域名，请看 @v2ray/domain-list-community 项目的 [data 文件夹](https://github.com/v2ray/domain-list-community/tree/master/data) 里每个类别里包含了什么域名。
