### ISSUE TITLE
开启代理，百度网盘下载无法写入

### ISSUE THREAD

**Issue by LHW6688** [Loyalsoldier/v2ray-rules-dat#100]
缺少百度网盘的规则，在开启代理之后，网盘下载的数据无法写入到文件，

**Comment by Loyalsoldier** [comment]
欢迎查看日志，看看百度网盘都用什么域名？

**Comment by LHW6688** [comment]
> 查看日志，看看百度网盘都用什么域名？

日志：
2021/04/06 16:57:23 127.0.0.1:59386 accepted http://update.pan.baidu.com/statistics?clienttype=8&devuid=6&channel=00&version=7.2.7.9&ver=1&id=16176991435DB8014C13A47E28FBEBF69F96&vip=0 [direct]
2021/04/06 16:57:23 [Warning] [2290883433] github.com/v2fly/v2ray-core/v4/proxy/http: failed to read response from update.pan.baidu.com > io: read/write on closed pipe

**Comment by Loyalsoldier** [comment]
baidu.com 及其子域名在直连列表里啊。
