### ISSUE TITLE
路由设置geosite:category-games@cn为直连，但steam没有效果

### ISSUE THREAD

**Issue by LikeARockStar** [Loyalsoldier/v2ray-rules-dat#102]
使用v2rayN 4.14客户端，路由配置如下：
"routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:category-games@cn",
          "domain:copymanga.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "proxy",
        "domain": [
          "geosite:google",
          "domain:mirror277.mangafunc.fun"
        ]
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all",
          "domain:localhost.iku.youku.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn",
          "domain:store.ubi.com",
          "domain:ol.epicgames.com",
          "domain:tracking.epicgames.com",
          "domain:example-example.com",
          "domain:example-example2.com"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:private",
          "geoip:cn"
        ]
      },
      {
        "type": "field",
        "port": "0-65535",
        "outboundTag": "proxy"
      }
    ]
  }
}
但是打开steam商店网页仍然走代理，steam客户端下载也是走代理

**Comment by Loyalsoldier** [comment]
我没在用 v2rayN，它支持用完整的路由配置文件？

**Comment by LikeARockStar** [comment]
> 我没在用 v2rayN，它支持用完整的路由配置文件？

v2rayN文件夹里的config.json，应该是完整的路由配置文件，抱歉我也不是很懂。
v2rayN路由功能正常，v2rayN文件夹里的geosite.dat也替换成了本项目里下载的，但geosite:category-games@cn和geosite:steam@cn都没有效果

**Comment by Loyalsoldier** [comment]
刚刚在 V2Ray v4.37.2 上测试了，`geosite:category-games@cn` 是可以成功解析为规则的。但是我没玩 Steam，不保证 `geosite:category-games@cn` 能涵盖所有国区游戏的域名。

如发现遗漏域名，欢迎到 https://github.com/v2fly/domain-list-community/issues 补充。

针对你这个问题，建议你到 v2rayN 提 issue。

**Comment by FoundTheWOUT** [comment]
v2rayN是支持几乎完整的路由配置的，但是需要打开`路由高级功能`，且进行一些小修改。所以，当然这个game规则也是能正常使用的，如果不行你可以尝试重启steam
