### ISSUE TITLE
路由规则

### ISSUE THREAD

**Issue by Jerryzcz** [Loyalsoldier/v2ray-rules-dat#107]
跳过大陆规则删除，如何再添加

**Comment by Loyalsoldier** [comment]
当初怎么添加的，现在就怎么添加啊。

**Comment by Jerryzcz** [comment]
OK，可以了，我更新了一些，规则就存在了，但出现一个问题是，我退出v2rayn后无法edge无法连接是怎么回事啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Loyalsoldier/v2ray-rules-dat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月15日(星期六) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Loyalsoldier/v2ray-rules-dat] 路由规则 (#107)





 
当初怎么添加的，现在就怎么添加啊。
