### ISSUE TITLE
block了win-spy之后,会导致edge无法同步,edge.activity.windows.com被NXDOMAIN

### ISSUE THREAD

**Issue by yeezylife** [Loyalsoldier/v2ray-rules-dat#108]
可是我前往 https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt 查看,这个列表里并没有edge.activity.windows.com这条域名啊

**Comment by yeezylife** [comment]
https://github.com/crazy-max/WindowsSpyBlocker/issues/339

他的issue里也有人反应了,但是他似乎言辞很激烈而且并没有修改..

**Comment by Loyalsoldier** [comment]
有 `activity.windows.com`

**Comment by yeezylife** [comment]
> 有 `activity.windows.com`

好吧，那edge用户没法用这个列表了…
