### ISSUE TITLE
[feature request] geoip and geosite containing IPs and domains for different types of DNS resolvers

### ISSUE THREAD

**Issue by molink36** [Loyalsoldier/v2ray-rules-dat#109]
I am using in my router v2ray in `fakedns `mode, and all udp and tcp connctions over port 53 are being redirected to v2ray. However, clients connected to the router still can do the following to bypass DNS server of v2ray:

1. Using traditional DNS over non-standard ports (UDP or TCP)
2. Using DNS over TLS (DoT) over standard and non-standard ports
3. Using DNS over HTTPS (DoH)
4. Using DNSCrypt (UDP or TCP)

In order to restrict clients to DNS server of v2ray, I plan to block IP addresses and domain names of all of the four mentioned above.

These are the lists that I have found so far:
DNS over HTTPS IPs:
https://github.com/oneoffdallas/dohservers/blob/master/iplist.txt
DNS over HTTPS Domains:
https://github.com/oneoffdallas/dohservers/blob/master/list.txt
DNS over TCP/UDP IPs:
https://github.com/0xrishabh/ActiveDns
DNSCrypt:
https://github.com/DNSCrypt/dnscrypt-resolvers
DNS over TLS:
I did not find a proper list for DNS over TLS.

It would be great if there was a `geoip `and `geosite` for DNS (for example `geoip:dns` and `geosite:dns` with subcategories for different kinds of DNS resolvers).

**Comment by Loyalsoldier** [comment]
The lists above are not convincing and hard to maintain, I'm afraid I will NOT implement this.
