### ISSUE TITLE
Win10商店，Win10自带天气，无法打开

### ISSUE THREAD

**Issue by Zeezorn** [Loyalsoldier/v2ray-rules-dat#11]
规则版本：Released on 202003032205（上几个老版本其实也打不开）
![微信截图_20200305095950](https://user-images.githubusercontent.com/31385055/75940542-5cb41f80-5ec8-11ea-8ed4-b5d9a780fc99.png)
![微信截图_20200305100058](https://user-images.githubusercontent.com/31385055/75940547-60e03d00-5ec8-11ea-910d-9f32cb083aef.png)

**Comment by Loyalsoldier** [comment]
参考：
https://blog.csdn.net/l1301913704/article/details/75009554
https://www.zhihu.com/question/48036877

**Comment by Zeezorn** [comment]
使用Fiddler问题解决
