### ISSUE TITLE
v2ray全局流量咨询

### ISSUE THREAD

**Issue by f1460330800** [Loyalsoldier/v2ray-rules-dat#110]
最近学习v2ray源码，咨询一下目前v2ray是否支持tun2socks，v2ray是否可以劫持所有本机流量，包括ssh，icmp等协议，目前测试时是无法支持ssh协议的，（设置全局代理，使用xshell直接连接被ban的ip，依旧无法连通）

**Comment by Loyalsoldier** [comment]
单单 V2Ray 不能劫持所有流量，但是可以与 tun2socks 或 iptables 等配合劫持所有流量。
