### ISSUE TITLE
[问题] 添加自定义域名的方法

### ISSUE THREAD

**Issue by leo2n** [Loyalsoldier/v2ray-rules-dat#111]
尊敬的开发者您好:
问题: 如何添加自定义域名进入geosite.dat;
已经找到的方法: 首先fork本项目, 在hidden分支的proxy.txt, direct.txt, reject.txt中添加域名, 然后使用github action, 最后下载更新后的geosite.dat, geoip.dat文件到本地v2ray `v2ray.location.asset` 所指定的目录或v2ray binary文件同目录;
疑问: 除此之外, 
1. 还有方法可以本地添加域名, 然后本地构建geosite.dat吗? 
2. 我查找了官方项目: https://github.com/v2fly/domain-list-community, 生成dlc.data后, 有没有什么方法可以合并本项目的geosite.dat, geoip.dat与dlc.data数据?
谢谢您😀

**Comment by Loyalsoldier** [comment]
看懂本项目的 GitHub Actions 脚本，你就知道如何在本地生成了。该 geosite.dat 已包含了官方项目中 dlc.dat 的内容。

**Comment by leo2n** [comment]
感谢回复
目前已经找到的方法: 使用geodata和geoip生成器, 参考地址: https://github.com/gamesofts/v2ray-custom-geo, 生成新的custom.dat, 然后在配置文件中, 使用"ext:filename:tag"的方法, 参考地址: https://www.v2fly.org/config/routing.html#routingobject, 在路由中添加.
