### ISSUE TITLE
反馈一个被误判的域名

### ISSUE THREAD

**Issue by fzhw88** [Loyalsoldier/v2ray-rules-dat#113]
hndpf.org，这是一个国内组织的网站，被判定成了国际组织要走代理，估计这个网站阻止了国际访问流量，所以现在只要开了代理就打不开这个站点。

**Comment by Loyalsoldier** [comment]
在已有的列表里没有找到这个域名啊。

**Comment by fzhw88** [comment]
> 在已有的列表里没有找到这个域名啊。

但的确开了绕过大陆的路由规则后这个站点就打不开了，ping也不通，只能关掉代理，已经试了多个环境。

**Comment by Loyalsoldier** [comment]
那就把它放进直连规则里。
