### ISSUE TITLE
v2ctl cannot load geoip:!cn

### ISSUE THREAD

**Issue by zyf0330** [Loyalsoldier/v2ray-rules-dat#114]
I use newest v2ctl.exe on Windows and geoip https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/202106092210/geoip.dat, execute v2ctl.exe config config.json.
 ```
v2ctl> Read config:  config.json
v2ray.com/core/infra/conf: failed to parse DNS config > v2ray.com/core/infra/conf: failed to build name server > v2ray.com/core/infra/conf: invalid ip rule: [geoip:!cn] > v2ray.com/core/infra/conf: failed to load GeoIP: !cn > v2ray.com/core/infra/conf: country not found in geoip.dat: !CN
```

**Comment by Loyalsoldier** [comment]
Please update your v2ray binary to the latest.

**Comment by zyf0330** [comment]
You are right. Website www.v2ray.com and Project V have stopped maintained.

**Comment by zyf0330** [comment]
You are right. Website www.v2ray.com and Project V have stopped maintained.

**Comment by Loyalsoldier** [comment]
V2Ray has been moved to https://github.com/v2fly/v2ray-core and https://www.v2fly.org
