### ISSUE TITLE
Add geosite:scholar-cn website that can get access in universities？

### ISSUE THREAD

**Issue by lxsjgzs** [Loyalsoldier/v2ray-rules-dat#116]
There are some scholar/research websites that can get access in some universities in CN. All of them add to rule can make the config file too long to read and inconvenient to be maintained. So here I collected some(not completely) scholar websites that can be accessed directly in universities. 

Thanks for your program!

#One line for per domain

elsevier.com
sciencedirect.com
ebscohost.com
springer.com
rsc.org
acs.org
aps.org
iop.org
nature.com
sciencemag.org
wiley.com
siam.org
osapublishing.org
specialsci.cn
oadds.cn
webofscience.com
cqvip.com
cnki.net

**Comment by lxsjgzs** [comment]
sciencemag.org

**Comment by Loyalsoldier** [comment]
I cannot confirm these. I recommend that you add these domains to your own configuration.

**Comment by lxsjgzs** [comment]
thx!
