### ISSUE TITLE
v2ray-docker报错country not found: google-cn

### ISSUE THREAD

**Issue by Ryanznoco** [Loyalsoldier/v2ray-rules-dat#117]
![image](https://user-images.githubusercontent.com/17562936/122661525-e838e900-d1bd-11eb-9dfa-5a5cc883c790.png)

**Comment by Loyalsoldier** [comment]
需要把 Docker 里的 geosite.dat 替换为从本项目下载的 geosite.dat

**Comment by Ryanznoco** [comment]
> 需要把 Docker 里的 geosite.dat 替换为从本项目下载的 geosite.dat

我是把一个目录挂载到docker的`/etc/v2ray`路径的，这个目录下有从本项目下载的geoip.dat和geosite.dat，以及一个config.json配置文件，这样是替换了的吧？

**Comment by Loyalsoldier** [comment]
显然是没有加载成功

**Comment by Ryanznoco** [comment]
> 显然是没有加载成功

那是为啥呢？我这个操作有问题吗？

**Comment by Loyalsoldier** [comment]
目录挂载错误吧。

**Comment by Ryanznoco** [comment]
> 目录挂载错误吧。

![image](https://user-images.githubusercontent.com/17562936/122917185-51705600-d390-11eb-9fbf-d082eb29f40f.png)
没有错啊，容器里/etc/v2ray目录下是有这三个文件的
