### ISSUE TITLE
在 Xray 的 DNS 模块中使用 "expectIPs": ["geoip:!cn"] 报错

### ISSUE THREAD

**Issue by GWONGJYULEI** [Loyalsoldier/v2ray-rules-dat#118]
报错内容如下：

> Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: failed to parse DNS config > infra/conf: failed to build nameserver > infra/conf: invalid IP rule: [geoip:!cn] > infra/conf: failed to load GeoIP: !cn > infra/conf: code not found in geoip.dat: !CN

**Comment by Loyalsoldier** [comment]
Xray 目前不支持类似 `geoip:!cn` 这种反向匹配

**Comment by terryzwt** [comment]
README里面提供了这sample，我没搞明白你咋搞定的？
@Loyalsoldier 

相关问题讨论如下：
https://github.com/v2ray/v2ray-core/issues/2177

![image](https://user-images.githubusercontent.com/1829399/130810959-e823546e-6165-40cd-86bd-d1cc50f91968.png)

**Comment by firerflystar** [comment]
> @terryzwt
> 
> [v2fly/v2ray-core#860](https://github.com/v2fly/v2ray-core/pull/860)

geoip:!cn
ext:/path/to/third-party/geoipfile:!cn
ext-ip:/path/to/third-party/geoipfile:!cn

这个文件geoipfile:!cn 是要自己去生成吗?

**Comment by Loyalsoldier** [comment]
@firerflystar 
这里演示的 geoipfile 是自定义 GeoIP 文件的意思。`!cn` 是 `cn` 列表，只是进行了反向匹配，即不匹配 `cn` 列表里的域名都命中这条规则。

**Comment by redstoneleo** [comment]
1. geoip:!cn这种写法在哪个客户端里可以用？
2. 我在v2rayN客户端里只写了geoip:cn，发现没有匹配的也自动走代理了，真神奇

**Comment by firerflystar** [comment]
> 1. geoip:!cn这种写法在哪个客户端里可以用？
> 2. 我在v2rayN客户端里只写了geoip:cn，发现没有匹配的也自动走代理了，真神奇

要检查下DNS的解析结果 解析出国外的IP就走代理了

**Comment by Cicedasay** [comment]
{
        "type": "field",
        "outboundTag": "VPS2",  // 使用VPS2
        "ip": [ // 基于IP分流
          "8.8.8.8/32",
          "geoip:telegram" //Xray只要添加了这个就无法启动，可以是"geoip:cn" :jp, :us之类就正常
        ]
      }
Xray只要ip分流里面主要有geoip:telegram这个规则就无法启动，可以是"geoip:cn" :jp, :us之类就正常。
