### ISSUE TITLE
建议所有Google域名归为国外

### ISSUE THREAD

**Issue by huxim** [Loyalsoldier/v2ray-rules-dat#119]
现在很多google-cn的域名虽然国内ip能ping通,但已不提供资源,比如fonts.googleapis.com和fonts.gstatic.com,下面这两个资源在国内ip上是找不到的,一些网站调用这些资源就会卡住
https://fonts.gstatic.com/s/notosanssc/v12/k3kXo84MPvpLmixcA63oeALhLOCT-xWNm8Hqd37g1OkDRZe7lR4sg1IzSy-MNbE9VH8V.118.woff2
https://fonts.googleapis.com/earlyaccess/notosanssc.css

**Comment by Loyalsoldier** [comment]
只要把 `geosite:google` 设置为走代理就行了。
