### ISSUE TITLE
有哪些使用风险？

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [Loyalsoldier/v2ray-rules-dat#12]
首先感谢作者的分享。提供这类科技服务大众的都是英雄。

话说回来，还是需要问一下，如果这个dat文件有被恶意修改的可能，有可能会造成哪些危险？
比如互联网数据泄漏？还是甚至有可能连接到恶意网站？
我是菜鸟，根据我的理解这类文件最多只能是访问有问题，会有其他危险没？

**Comment by Loyalsoldier** [comment]
又不会咬人，有啥危险。

**Comment by fbion** [comment]
可以自定义
https://github.com/v2ray/discussion/issues/592
