### ISSUE TITLE
反馈一个域名错误分类问题

### ISSUE THREAD

**Issue by Zerorigin** [Loyalsoldier/v2ray-rules-dat#120]
tongji.baidu.com 是百度站长统计，类似谷歌站长和必应站长，只是一个站长的网站统计后台管理系统，并未提供广告发放及隐私数据追踪（百度是使用 hm.baidu.com 此域名下的接口提供访问追踪的），但是却被分类到了 "geosite.dat:category-ads-all"。希望能将 tongji.baidu.com 从其中排除掉。因为现在用 “geosite.dat:category-ads-all” 做广告过滤，导致无法访问 tongji.baidu.com。
.

**Comment by Loyalsoldier** [comment]
感谢反馈，已移除 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/4fdfd100836f2e5a68e05c7f789762ea0d0c42b6
