### ISSUE TITLE
geoip.dat大小从5M左右激增到48M，路由器上跑的v2ray运行后直接掉出了

### ISSUE THREAD

**Issue by rendaa** [Loyalsoldier/v2ray-rules-dat#123]
如题……
是从 202107292210那个release开始变大的，不知加了什么内容导致文件变这么大？
可否弄个小点儿的给比较弱小的设备用……

**Comment by Loyalsoldier** [comment]
原因：https://github.com/Loyalsoldier/geoip/issues/31#issuecomment-888942229

解决办法：https://www.v2fly.org/config/env.html#geodata-%E6%96%87%E4%BB%B6%E5%8A%A0%E8%BD%BD%E5%99%A8

**Comment by darkless456** [comment]
https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat  

这个地址提示 `File size exceeded the configured limit of 20 MB.`

**Comment by rendaa** [comment]
> 原因：[Loyalsoldier/geoip#31 (comment)](https://github.com/Loyalsoldier/geoip/issues/31#issuecomment-888942229)
谢谢解释。



> 解决办法：https://www.v2fly.org/config/env.html#geodata-%E6%96%87%E4%BB%B6%E5%8A%A0%E8%BD%BD%E5%99%A8
使用46M的geoip.dat，运行v2ray前用下面命令设置了环境变量V2RAY_CONF_GEOLOADER：

	export V2RAY_CONF_GEOLOADER=memconservative

然后运行v2ray，感觉很慢，两分半后还是掉出了（12:16:54开始运行，至12:18:26掉出），其间v2ray的侦听端口一直没打开过。
输出如下：

V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/arm)
A unified platform for anti-censorship.
2021/08/01 12:16:54 [Info] main/jsonem: Reading config: /opt/v2ray/config.json
2021/08/01 12:17:33 [Debug] app/log: Logger started
2021/08/01 12:18:03 [Info] app/dns: DNS: created Remote DOH client for https://1.1.1.1/dns-query
2021/08/01 12:18:06 [Info] app/dns: DNS: created UDP client initialized for 8.8.8.8:53
2021/08/01 12:18:06 [Info] app/dns: DNS: created UDP client initialized for 114.114.114.114:53
2021/08/01 12:18:26 [Info] app/dns: DNS: created localhost client
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x9501d7, 0x16)
        runtime/panic.go:1117 +0x5c
runtime.sysMap(0xf400000, 0x1800000, 0xf2c068)
        runtime/mem_linux.go:169 +0xb0
runtime.(*linearAlloc).alloc(0xf1c680, 0x1800000, 0x400000, 0xf2c068, 0x0)
        runtime/malloc.go:1431 +0x94
runtime.(*mheap).sysAlloc(0xf1c588, 0x1800000, 0x7fffffff, 0x40163000)
        runtime/malloc.go:635 +0x54
runtime.(*mheap).grow(0xf1c588, 0xb89, 0x0)
        runtime/mheap.go:1346 +0x6c
runtime.(*mheap).allocSpan(0xf1c588, 0xb89, 0x10100, 0x10001c0)
        runtime/mheap.go:1173 +0x5e0
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:910 +0x48
runtime.systemstack(0x1040480)
        runtime/asm_arm.s:347 +0x84
runtime.mstart()
        runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
        runtime/asm_arm.s:294 +0x4 fp=0x1a7d890 sp=0x1a7d88c pc=0x7c584
runtime.(*mheap).alloc(0xf1c588, 0xb89, 0x101, 0x0)
        runtime/mheap.go:904 +0x58 fp=0x1a7d8b4 sp=0x1a7d890 pc=0x38854
runtime.(*mcache).allocLarge(0x4008e088, 0x1710590, 0x101, 0x0)
        runtime/mcache.go:224 +0x78 fp=0x1a7d8e4 sp=0x1a7d8b4 pc=0x26aa8
runtime.mallocgc(0x1710590, 0x88c018, 0x14f01, 0xf282000)
        runtime/malloc.go:1078 +0x9c4 fp=0x1a7d944 sp=0x1a7d8e4 pc=0x1caec
runtime.makeslice(0x88c018, 0x0, 0x171059, 0xf282000)
        runtime/slice.go:98 +0x6c fp=0x1a7d958 sp=0x1a7d944 pc=0x607a8
github.com/v2fly/v2ray-core/v4/app/router.(*GeoIPMatcher).Init(0xe9bd340, 0x5a00000, 0x182bd3, 0x1bc000, 0x868210, 0x1f0)
        github.com/v2fly/v2ray-core/v4/app/router/condition_geoip.go:61 +0x234 fp=0x1a7d9c4 sp=0x1a7d958 pc=0x56e2cc
github.com/v2fly/v2ray-core/v4/app/router.(*GeoIPMatcherContainer).Add(0xf16e00, 0x3a99620, 0x4008e088, 0x40, 0xe9bd300)
        github.com/v2fly/v2ray-core/v4/app/router/condition_geoip.go:197 +0x134 fp=0x1a7da00 sp=0x1a7d9c4 pc=0x56f220
github.com/v2fly/v2ray-core/v4/app/router.NewMultiGeoIPMatcher(0x2762140, 0x8, 0x8, 0xe9bd300, 0x0, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/app/router/condition.go:125 +0x68 fp=0x1a7da3c sp=0x1a7da00 pc=0x56cf6c
github.com/v2fly/v2ray-core/v4/app/router.(*RoutingRule).BuildCondition(0x108def0, 0xf116ba0, 0xe9ca940, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/app/router/config.go:116 +0xa74 fp=0x1a7db3c sp=0x1a7da3c pc=0x570024
github.com/v2fly/v2ray-core/v4/app/router.(*Router).Init(0x2762260, 0xa6ac6c, 0x1282048, 0x275b380, 0x507ed650, 0x2760730, 0x507ed670, 0x2764200, 0x18, 0x79250)
        github.com/v2fly/v2ray-core/v4/app/router/router.go:50 +0x428 fp=0x1a7dbac sp=0x1a7db3c pc=0x573bec
github.com/v2fly/v2ray-core/v4/app/router.init.1.func1.1(0x507ed650, 0x2760730, 0x507ed670, 0x2764200, 0x0, 0x0)
        github.com/v2fly/v2ray-core/v4/app/router/router.go:146 +0x64 fp=0x1a7dbd8 sp=0x1a7dbac pc=0x574bac
runtime.call32(0xbd0f980, 0x1282060, 0xbd20390, 0x18, 0x10)
        runtime/asm_arm.s:510 +0x4c fp=0x1a7dbfc sp=0x1a7dbd8 pc=0x7c9dc
reflect.Value.call(0x840fe0, 0x1282060, 0x13, 0x9406dd, 0x4, 0xbd20348, 0x2, 0x2, 0x2, 0xc, ...)
        reflect/value.go:476 +0x62c fp=0x1a7dcfc sp=0x1a7dbfc pc=0xe11b4
reflect.Value.Call(0x840fe0, 0x1282060, 0x13, 0xbd20348, 0x2, 0x2, 0x1, 0x2, 0x60b04)
        reflect/value.go:337 +0x78 fp=0x1a7dd38 sp=0x1a7dcfc pc=0xe09a0
github.com/v2fly/v2ray-core/v4.(*resolution).resolve(0x1a7de40, 0x27643c0, 0x6, 0x8, 0x1, 0xbd20330, 0x0)
        github.com/v2fly/v2ray-core/v4/v2ray.go:74 +0x504 fp=0x1a7ddec sp=0x1a7dd38 pc=0x3fd8f4
github.com/v2fly/v2ray-core/v4.(*Instance).AddFeature(0x275b290, 0x507ed630, 0x2760730, 0x507ed630, 0x2760730)
        github.com/v2fly/v2ray-core/v4/v2ray.go:305 +0xfc fp=0x1a7de54 sp=0x1a7ddec pc=0x3fee2c
github.com/v2fly/v2ray-core/v4.initInstanceWithConfig(0x1312550, 0x275b290, 0x0, 0x0, 0x849b01)
        github.com/v2fly/v2ray-core/v4/v2ray.go:201 +0x100 fp=0x1a7dedc sp=0x1a7de54 pc=0x3fe230
github.com/v2fly/v2ray-core/v4.New(0x1312550, 0x4, 0xbec65d37, 0x16)
        github.com/v2fly/v2ray-core/v4/v2ray.go:164 +0x60 fp=0x1a7defc sp=0x1a7dedc pc=0x3fe0bc
main.startV2Ray(0x1064180, 0x1024020, 0x2, 0x2)
        github.com/v2fly/v2ray-core/v4/main/main.go:115 +0x260 fp=0x1a7df4c sp=0x1a7defc pc=0x7b0e60
main.main()
        github.com/v2fly/v2ray-core/v4/main/main.go:139 +0x98 fp=0x1a7dfb8 sp=0x1a7df4c pc=0x7b1174
runtime.main()
        runtime/proc.go:225 +0x26c fp=0x1a7dfe4 sp=0x1a7dfb8 pc=0x4a9ec
runtime.goexit()
        runtime/asm_arm.s:841 +0x4 fp=0x1a7dfe4 sp=0x1a7dfe4 pc=0x7e28c


换回一较早的5M的geoip.dat再运行，从启动程序到可以用梯子，时间不到一分钟。

恐怕还是需要考虑发布个轻量版的geoip.dat……

**Comment by Loyalsoldier** [comment]
@rendaa 麻烦列出设备的硬件配置和系统配置

**Comment by rendaa** [comment]
> @rendaa 麻烦列出设备的硬件配置和系统配置

路由器硬件型号 NetGear R6300v2，CPU 是 Broadcom BCM4708，256M内存。固件刷的是 TomatoUSB shibby 版（Tomato v1.28.0000 -140 K26ARM USB AIO-64K）。
这货用得有点久了，这固件从2017年后也不再更新了，但因为嫌重新配很多东西麻烦、用着也够，就没换硬件也没刷别的固件。


```
# cat /proc/cpuinfo 
Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 1599.07

processor       : 1
BogoMIPS        : 1595.80

Features        : swp half thumb fastmult edsp 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000

# uname -a
Linux Router 2.6.36.4brcmarm #17 SMP PREEMPT Wed Apr 19 15:29:02 CEST 2017 armv7l GNU/Linux

# cat /proc/meminfo
MemTotal:         255632 kB
MemFree:          105468 kB
Buffers:            5800 kB
Cached:            46244 kB
SwapCached:         1912 kB
Active:            74696 kB
Inactive:          40160 kB
Active(anon):      61872 kB
Inactive(anon):     3172 kB
Active(file):      12824 kB
Inactive(file):    36988 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:         72288 kB
SwapFree:          65520 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         61312 kB
Mapped:            12552 kB
Shmem:              2232 kB
Slab:              21540 kB
SReclaimable:       1812 kB
SUnreclaim:        19728 kB
KernelStack:         688 kB
PageTables:          852 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      200104 kB
Committed_AS:     120904 kB
VmallocTotal:     516096 kB
VmallocUsed:       18288 kB
VmallocChunk:     426392 kB

# v2ray --version
V2Ray 4.40.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.5 linux/arm)
A unified platform for anti-censorship.

# ps aux|grep v2ray （下面标题行是自己加的）
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     20789  1.6 22.8 812300 58320 ?        Sl   Aug01  22:54 /opt/v2ray/v2ray -config /opt/v2ray/config.json

```

**Comment by f1ume** [comment]
我在windows上用，刚启动就占内存六七百M，这也太夸张了。虽然会缓慢降下来。还是找了最后一个5M的版本换上去，启动才一百多M
