### ISSUE TITLE
最新的两次更新，Qv2ray 运行报错。

### ISSUE THREAD

**Issue by JoeyVan** [Loyalsoldier/v2ray-rules-dat#125]
![image](https://user-images.githubusercontent.com/3583503/127830692-141bda29-836b-4962-8893-8c2af52a743d.png)
如图。不知该如何解决。谢谢。

**Comment by Loyalsoldier** [comment]
请通过此地址来下载 geoip.dat 文件：https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
