### ISSUE TITLE
自己添加GFW模式联不通

### ISSUE THREAD

**Issue by Omoinemie** [Loyalsoldier/v2ray-rules-dat#126]
错误提示：Failed to start: main: failed to load config files: [D:\APP\VPN\v2rayN\config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: netflix > infra/conf: code not found in geoip.dat: NETFLIX

自定义路由规则代码：
`[
  {
     "outboundTag": "proxy",
     "ip": [
       "geoip:telegram"
     ],
     "domain": [
       "geosite:gfw"
    ]
  },
  {
    "port": "0-65535",
    "outboundTag": "direct"
  }
]`

**Comment by IIIlllIIllIIIll** [comment]
尝试更新一下geoip.dat

**Comment by Omoinemie** [comment]
> 尝试更新一下`geoip.dat`

怎么GFW模式没生效，网站还是直连的，哪里出错了？
2021/08/08 20:10:29 127.0.0.1:10159 accepted //r3---sn-i3belnlz.googlevideo.com:443 [direct]

**Comment by IIIlllIIllIIIll** [comment]
> > 尝试更新一下`geoip.dat`
> 
> 怎么GFW模式没生效，网站还是直连的，哪里出错了？
> 2021/08/08 20:10:29 127.0.0.1:10159 accepted //r3---sn-i3belnlz.googlevideo.com:443 [direct]
当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。即 ```domains``` 和 ```ip``` 规则需要分开使用。

**Comment by Omoinemie** [comment]
> > > 尝试更新一下`geoip.dat`
> > 
> > 
> > 怎么GFW模式没生效，网站还是直连的，哪里出错了？
> > 2021/08/08 20:10:29 127.0.0.1:10159 accepted //r3---sn-i3belnlz.googlevideo.com:443 [direct]
> 
> 当多个属性同时指定时，这些属性需要同时满足，才可以使当前规则生效。即 `domains` 和 `ip` 规则需要分开使用。

我改成这种就可以了，这有什么区别？
geosite:gfw,
geosite:greatfire,
geosite:tld-!cn,
geosite:geolocation-!cn

**Comment by IIIlllIIllIIIll** [comment]
```geoip:telegram```是IP规则
