### ISSUE TITLE
Geosite文件内错误将tiktok.com归为CN，导致无法访问

### ISSUE THREAD

**Issue by Sherman-Liu** [Loyalsoldier/v2ray-rules-dat#128]
如题，在本项目下载的geosite.dat，开启绕过Geosite:CN后，tiktok.com被错误分类为CN绕过，导致无法访问且提示连接被中断，关闭Geosite:CN后正常访问。

预期目标：tiktok.com及相关域名不应被包括在CN类别内。

**Comment by Loyalsoldier** [comment]
已知问题。建议把 `geosite:tiktok` 设置为代理

**Comment by jiuqianyuan** [comment]
同样的问题，建议及时修正
