### ISSUE TITLE
建议剔除常见直连且速度不错的网站，比如baidu.cn和qpic.cn

### ISSUE THREAD

**Issue by o0HalfLife0o** [Loyalsoldier/v2ray-rules-dat#13]
rt

**Comment by Loyalsoldier** [comment]
建议是好建议，但是由于上游域名列表由第三方进行维护（不是特别准确，有陈旧的、有遗漏的）。比对 direct 和 proxy 列表后发现，无论从哪个列表剔除另一个列表的重复域名，多多少少都有不合适的域名存在于不合适的列表中。但是一般都不是什么访问量大的域名。`ifanr.com` 是个特例，已给上游域名列表项目提交 issue。

过几天看看上游项目有没有回应。没有回应的话，届时我手动处理一下 `ifanr.com` 这个域名。

**Comment by 523860169** [comment]
理解并感谢

**Comment by Loyalsoldier** [comment]
已从 proxy-list 移除 `ifanr.com`

**Comment by o0HalfLife0o** [comment]
以下域名通过17ce检测也是都可以直连，并且速度不错的
apple.com.cn
apple.com
apple.cn
baidu.cn
bjnews.com.cn
businesstimes.com.cn
google.cn
googleapis.cn
gstatic.cn
scholar.google.com.cn
qpic.cn
www.chromes.cn

**Comment by Loyalsoldier** [comment]
Apple、Google、Microsoft 等国内可访问的国外大公司的域名或服务，本项目统一使用 `proxy` 策略。有直连需求的，请在自己的配置文件中 `proxy` 策略的前面添加域名类的直连规则（规则越前，优先级较高），类似这样：

```
"routing": {
  "rules": [
    {
      "type": "field",
      "outboundTag": "Direct",
      "domain": [
        "domain:apple.cn",
        "domain:apple.com.cn",
        "domain:google.cn",
      ]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": [
        "geosite:geolocation-!cn"
      ]
    },
  ]
}
```

其他域名我查一下上游项目。

**Comment by Loyalsoldier** [comment]
已将所有以 `.cn` 顶级域结尾的域名从 `proxy-list` 中移除。
