### ISSUE TITLE
求助：如何将脚本中的原仓库替换为此仓库

### ISSUE THREAD

**Issue by Lather0519** [Loyalsoldier/v2ray-rules-dat#130]
如下图所说，可以修改脚本改变指向仓库，我发现无法通过此github主页找到指向该仓库的地址，请问应该如何改写这段脚本？

> `sed -i 's/^\turl_main.*/\turl_main="https:\/\/raw.githubusercontent.com\/qxzg\/Actions\/master\/fancyss_rules"/g' /koolshare/scripts/ss_rule_update.sh`

![image](https://user-images.githubusercontent.com/32637838/130033684-97eaa78d-6f32-4406-b9fe-cafb986013ae.png)

**Comment by Loyalsoldier** [comment]
学 sed 和 awk
