### ISSUE TITLE
添加微软网络状态探测域名

### ISSUE THREAD

**Issue by kgpg** [Loyalsoldier/v2ray-rules-dat#136]
建议microsoft分类添加：www.msftconnecttest.com 和 www.msftncsi.com
这两个是微软探测是否成功连接到网络的域名，详见：https://docs.microsoft.com/en-US/troubleshoot/windows-client/networking/internet-explorer-edge-open-connect-corporate-public-network

Windows 10 或更高版本：
    NCSI 发送 DNS 请求以解析 www.msftconnecttest.comFQDN。
    如果 NCSI 收到来自 DNS 服务器的有效响应，NCSI 会发送一个普通的 HTTP GET 请求到 http://www.msftconnecttest.com/connecttest.txt.

Windows 8.1 或更早版本：
    NCSI 发送 DNS 请求以解析 www.msftncsi.comFQDN。
    如果 NCSI 收到来自 DNS 服务器的有效响应，NCSI 会发送一个普通的 HTTP GET 请求到 http://www.msftncsi.com/ncsi.txt.
    如果 NCSI 成功下载文本文件，它会确保该文件包含 Microsoft NCSI。

**Comment by Loyalsoldier** [comment]
Merged in https://github.com/v2fly/domain-list-community/pull/610
