### ISSUE TITLE
反馈个谷歌商店下载的等待中的情况

### ISSUE THREAD

**Issue by nnkn** [Loyalsoldier/v2ray-rules-dat#137]
最近换了手机，顺便把库更新了一下，结果谷歌商店下载老是在等待中。
经排查，发现去掉`绕过国内域名`的规则就可以下载
于是我在这个规则前面加了个`谷歌域名全部走代理`，两个都启用，一切正常了
有点怀疑国内域名库是不是加进了谷歌域名了呀？
不会看源码，还得大佬来排查一下。
app用的AnXray https://github.com/XTLS/AnXray/releases/tag/0.3-rc03

**Comment by Loyalsoldier** [comment]
已知问题，感谢反馈。
