### ISSUE TITLE
使用黑名单模式会让一 IP 签名工具走代理

### ISSUE THREAD

**Issue by DustinWin** [Loyalsoldier/v2ray-rules-dat#140]
设置黑名单模式后，如："domain": ["geosite:tld-!cn", "geosite:gfw", "geosite:greatfire"]，会让 [https://tool.lu/netcard/](url) 网站走代理，导致 IP 显示在国外。

**Comment by IIIlllIIllIIIll** [comment]
.lu 是卢森堡大公国的顶级域名，包含在```tld-!cn```

**Comment by Loyalsoldier** [comment]
去除 `geosite:tld-!cn` 即可。已更新 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/106d799bf3b4853283def2975001bc799ead3e97

**Comment by DustinWin** [comment]
> .lu 是**卢森堡大公国**的顶级域名，包含在`tld-!cn`。

原来如此，感谢！

**Comment by DustinWin** [comment]
> 去除 `geosite:tld-!cn` 即可。已更新 [106d799](https://github.com/Loyalsoldier/v2ray-rules-dat/commit/106d799bf3b4853283def2975001bc799ead3e97)

嗯，好的，感谢！
