### ISSUE TITLE
geoip在cdn中是否适用？

### ISSUE THREAD

**Issue by Murphylu1993** [Loyalsoldier/v2ray-rules-dat#142]
如题，比图netflix的geoip是根据asn的CIDR生成的吧，那么在CDN环境中这些CIDR应该就不匹配原先的geoip了吧，而这些流媒体大部分都走cdn的

**Comment by Loyalsoldier** [comment]
CDN 域名解析到自己拥有的 CIDR 不就行了吗，怎么不适用
