### ISSUE TITLE
想问一下geodat和geoip里所有的类别目录可以在哪里查看？

### ISSUE THREAD

**Issue by raphael008** [Loyalsoldier/v2ray-rules-dat#146]
v2ray-core里原版的geodat相关文档里附了一份全部的类别名称目录，在这个repo介绍里只看到了一部分类别名称，不知道在哪里看所有的类别名称，望指点。

**Comment by Loyalsoldier** [comment]
geoip 所有类别：https://github.com/Loyalsoldier/geoip/tree/release/text

原本 geosite 类别：https://github.com/v2fly/domain-list-community/tree/master/data
另外，本项目中 geosite.dat 包含 README 里新增的类别。

**Comment by Loyalsoldier** [comment]
> 看了连接中的geoip.dat 所有类别，都是缩写，我想筛选中国的家庭ipv6段，用哪个，主要是移动的

中国大陆 IP 地址列表：https://github.com/Loyalsoldier/geoip/blob/release/text/cn.txt

**Comment by BBplux** [comment]
> geoip.dat 所有类别：https://github.com/Loyalsoldier/geoip/tree/release/text
> 
> 原本 geosite.dat 类别：https://github.com/v2fly/domain-list-community/tree/master/data 另外，本项目中 geosite.dat 除了包含原本的所有类别，也包含 README 里新增的类别。

lan和private为什么找不到

**Comment by Loyalsoldier** [comment]
@BBplux 

本项目没有 `lan` 类别。有些 app 内置了 lan，例如 Clash，有些没有。

`private` 在 https://github.com/Loyalsoldier/geoip/blob/release/text/private.txt
