### ISSUE TITLE
具体怎么用啊，不知道我用的对不对，搞不太清楚

### ISSUE THREAD

**Issue by ytdhblk227** [Loyalsoldier/v2ray-rules-dat#148]
是不是把geoip和geosite下载后替换原文件之后，高级路由打开选择绕过大陆模式就行吗？
怎么用原来的PAC模式呢？自建规则怎么搞
复制这些代码从粘贴板导入没有规则生成啊
纯小白，望大神不吝赐教

**Comment by Loyalsoldier** [comment]
v2rayN 最简单的用法就是下载 geoip.dat 和 geosite.dat，选择绕过大陆模式。
本项目中的配置是 v2ray 的配置，不能直接复制粘贴到 v2rayN。
v2rayN 的使用问题请到 v2rayN 项目提问。
