### ISSUE TITLE
谷歌服务被错误分流到geosite:cn

### ISSUE THREAD

**Issue by dnomd343** [Loyalsoldier/v2ray-rules-dat#151]
在谷歌play安装app时，发现开启分流后无法下载，查询日志发现 `services.googleapis.cn` 域名被路由发送到 direct 直连出口，而该域名本身被SNI阻断无法连接，从而导致play商店异常，在数台手机（系统语言为简体中文）都观察到以上问题。

因此，`services.googleapis.cn` 域名应从 geosite:cn 中移除，避免风流错误发生。

**Comment by Loyalsoldier** [comment]
建议在 `geosite:cn` 规则前自行添加 `geosite:google` 规则走代理。
