### ISSUE TITLE
容易误解的README内容

### ISSUE THREAD

**Issue by StoneMoe** [Loyalsoldier/v2ray-rules-dat#153]
在README中的`规则文件生成方式 -> geosite.dat`部分有这样一段
```
@felixonmars/dnsmasq-china-list/accelerated-domains.china.conf 加入到 geosite:cn 类别中
@felixonmars/dnsmasq-china-list/apple.china.conf 加入到 geosite:geolocation-!cn 类别中（如希望本文件中的 Apple 域名直连，请参考下面 geosite 的 Routing 配置方式）
@felixonmars/dnsmasq-china-list/google.china.conf 加入到 geosite:geolocation-!cn 类别中（如希望本文件中的 Google 域名直连，请参考下面 geosite 的 Routing 配置方式）
```

其中描述仅`accelerated-domains.china.conf` 被加入了 `geosite:cn`，`google.china.conf`和`apple.china.conf`则未被加入到`geosite:geolocation-!cn`中

但实际情况如您在 https://github.com/Loyalsoldier/surge-rules/issues/12 中描述为，`google.china.conf`存在于`geosite:cn`中，而`apple.china.conf`的集成情况未知

希望能优化一下README的描述文本和组织结构，以减少歧义与理解难度

**Comment by Loyalsoldier** [comment]
抱歉，之前我搞错了。google.china.conf 和 apple.china.conf 存在于上游项目的 geosite:geolocation-!cn 中。
