### ISSUE TITLE
填写steam直连规则后还有部分steam域名没有命中

### ISSUE THREAD

**Issue by asranzalla** [Loyalsoldier/v2ray-rules-dat#155]
系统为manjaro gnome，客户端为qv2ray 2.7 appimage版本。pacman安装v2ray带了两个社区仓库的依赖domain-list-community和geoip，我使用提供下载的dat文件替换了，之后在qv2ray高级路由设置中设定了如下直连：
`store.steampowered.com
geosite:steam@cn
geosite:category-games@cn`
重启qv2ray和steam后发现下载似乎不走代理了但还有部分steam域名未命中，似乎主要是steam-chat.com和包含akamai的域名，请问该如果处理？

`2021/11/22 04:19:39 127.0.0.1:60974 accepted //media.st.dl.pinyuncloud.com:443 [DIRECT]
2021/11/22 04:19:39 127.0.0.1:60976 accepted //media.st.dl.pinyuncloud.com:443 [DIRECT]
2021/11/22 04:19:48 127.0.0.1:60978 accepted //store.steampowered.com:443 [DIRECT]
2021/11/22 04:19:51 127.0.0.1:60980 accepted //browser.pipe.aria.microsoft.com:443 [BLACKHOLE]
2021/11/22 04:19:51 127.0.0.1:60982 accepted //browser.pipe.aria.microsoft.com:443 [BLACKHOLE]
2021/11/22 04:19:55 127.0.0.1:60984 accepted //browser.pipe.aria.microsoft.com:443 [BLACKHOLE]
2021/11/22 04:19:55 127.0.0.1:60986 accepted //browser.pipe.aria.microsoft.com:443 [BLACKHOLE]
2021/11/22 04:20:02 127.0.0.1:60988 accepted //redirector.gvt1.com:443 [DIRECT]
2021/11/22 04:20:02 127.0.0.1:60990 accepted //r1---sn-2x3eenee.gvt1.com:443 [PROXY]
2021/11/22 04:20:04 127.0.0.1:60992 accepted //steamcommunity.com:443 [PROXY]
2021/11/22 04:20:07 127.0.0.1:60994 accepted //community.akamai.steamstatic.com:443 [PROXY]
2021/11/22 04:20:07 127.0.0.1:60996 accepted //community.akamai.steamstatic.com:443 [PROXY]
2021/11/22 04:20:07 127.0.0.1:60998 accepted //community.akamai.steamstatic.com:443 [PROXY]
2021/11/22 04:20:07 127.0.0.1:32768 accepted //community.akamai.steamstatic.com:443 [PROXY]
2021/11/22 04:20:07 127.0.0.1:32770 accepted //community.akamai.steamstatic.com:443 [PROXY]
2021/11/22 04:20:07 127.0.0.1:32772 accepted //community.akamai.steamstatic.com:443 [PROXY]
2021/11/22 04:20:40 127.0.0.1:32774 accepted //static.asm.skype.com:443 [PROXY]
2021/11/22 04:20:41 127.0.0.1:32776 accepted //static-asm.secure.skypeassets.com:443 [PROXY]
2021/11/22 04:20:44 127.0.0.1:32778 accepted //steamcdn-a.akamaihd.net:443 [PROXY]
2021/11/22 04:20:44 127.0.0.1:32780 accepted //steamcdn-a.akamaihd.net:443 [PROXY]`

**Comment by Loyalsoldier** [comment]
我没有在玩 Steam。上面代理的域名有用于游戏下载的吗？

**Comment by asranzalla** [comment]
下载时好像并没有跑很多流量，但是下载过程中会参与进来，比如获取下载信息之类的时候，但是akamai的域名有不少，并不能分辨每个是干嘛的跑了多少流量
