### ISSUE TITLE
switch 国行游戏机 无法观看 腾讯视频 被屏蔽了

### ISSUE THREAD

**Issue by JSZMonkey** [Loyalsoldier/v2ray-rules-dat#156]
switch 国行游戏机 无法观看 腾讯视频 被屏蔽了，移动端 优酷 也被屏蔽了

**Comment by Loyalsoldier** [comment]
是上游的广告规则的问题。本项目不特殊处理广告规则。遇到问题，建议不要屏蔽广告，或将相关域名设置为直连。
