### ISSUE TITLE
Google 在中国大陆可直连的域名列表 google-cn.txt建议删除--full:ssl.gstatic.com

### ISSUE THREAD

**Issue by Garindu** [Loyalsoldier/v2ray-rules-dat#157]
北方联通。

full:ssl.gstatic.com这个在v2ray路由直连的话，会造成无法登录google，但是登录之后无影响使用google无影响。

**Comment by Loyalsoldier** [comment]
建议把 Google 相关的域名加入到代理规则，或把 `geosite:google-cn` 设置为代理，并处于 `geosite:cn` 之前。
