### ISSUE TITLE
telegram分流不准确

### ISSUE THREAD

**Issue by stonegr** [Loyalsoldier/v2ray-rules-dat#160]
geoip和
geosite都添加到block，
route已设置IPIfNonMatch
telegram还是可以联通，(比正常慢一点，转一会儿就自己连通了)

**Comment by IIIlllIIllIIIll** [comment]
两分钟连不上，不能复现。我把v4和v6地址分开放，所以有```ext:geoip6.dat:telegram```。
```json
      {
        "type": "field",
        "outboundTag": "Block",
        "ip": [
          "geoip:telegram",
          "ext:geoip6.dat:telegram"
        ]
      }
```

**Comment by stonegr** [comment]
> 谢谢大佬回复，这个只需要弄ip就好了吗？geosite是不是不用设置？

**Comment by stonegr** [comment]
> 两分钟连不上，不能复现。我把v4和v6地址分开放，所以有`ext:geoip6.dat:telegram`。
> 
> ```json
>       {
>         "type": "field",
>         "outboundTag": "Block",
>         "ip": [
>           "geoip:telegram",
>           "ext:geoip6.dat:telegram"
>         ]
>       }
> ```

你好，我测试了以下
![image](https://user-images.githubusercontent.com/74632994/144830692-be16beaa-117a-4c9d-acdb-3cb86a385b57.png)
依旧不行，请问geoip6.dat有下载连接吗？我没找到，自己找的ipv6地址也不全，谢谢

**Comment by IIIlllIIllIIIll** [comment]
> > 两分钟连不上，不能复现。我把v4和v6地址分开放，所以有`ext:geoip6.dat:telegram`。
> > ```json
> >       {
> >         "type": "field",
> >         "outboundTag": "Block",
> >         "ip": [
> >           "geoip:telegram",
> >           "ext:geoip6.dat:telegram"
> >         ]
> >       }
> > ```
> 
> 你好，我测试了以下 ![image](https://user-images.githubusercontent.com/74632994/144830692-be16beaa-117a-4c9d-acdb-3cb86a385b57.png) 依旧不行，请问geoip6.dat有下载连接吗？我没找到，自己找的ipv6地址也不全，谢谢

我的```geoip6.dat```就是拆出来，只有v6的```geoip.dat```。是不是前面有其他规则分走了，为什么不用```geoip:telegram```？

**Comment by Loyalsoldier** [comment]
下载本项目最新的 geoip.dat，在配置中使用 `geoip:telegram` 即可。
