### ISSUE TITLE
Google Apple 域名使用 domain 匹配

### ISSUE THREAD

**Issue by IrineSistiana** [Loyalsoldier/v2ray-rules-dat#163]
目前是 full 匹配。

https://github.com/Loyalsoldier/v2ray-rules-dat/blob/467b44b7605cf3e8de7c9c16080b18b45b4bbae5/.github/workflows/run.yml#L156-L159

导致大量带子域名的域名无法匹配。比如 

apple list 有 `phobos.apple.com` 但 `full:phobos.apple.com` 匹配不了 `a100.phobos.apple.com` 

是不是应该和其他来自 dnsmasq-china-list 的域名一样使用 domain 匹配。

**Comment by Loyalsoldier** [comment]
当初是因为这个问题而改成 `full:` 类型的：https://github.com/v2fly/domain-list-community/issues/374

**Comment by IrineSistiana** [comment]
这种问题挺无解的...没有完美的域名表...

个人想法: 因为 dnsmasq-china-list 所有域名都是 domain 匹配，很多项目都在用，如果 geosite 里变成 full 匹配的话容易让人误解。如果能和 dnsmasq-china-list 保持统一的话，有问题的域名可以提交到 dnsmasq-china-list 不用在这里单独处理了，geosite 的数据也能和上游保持一致。

**Comment by Loyalsoldier** [comment]
想起来，还有另外一种情况：

因为上游 @v2fly/domain-list-community 的 apple 和 google 列表中有诸如 `full:apple.cn @cn` 这样的规则（同样来自 dnsmasq-china-list），但是添加了 `full:`。

如果本项目取消了 apple-cn 和 google-cn 列表的 `full:`，会导致如果在 V2Ray 的 DNS 中使用下面的配置，`geosite:apple-cn` 和 `geosite:google-cn` 会匹配失败。因为 DNS 规则匹配中，full 规则优先级最高。

```json
"dns": {
  "servers": [
    {
      "address": "114.114.114.114",
      "domains": ["geosite:apple-cn", "geosite:google-cn"]
    },
    {
      "address": "1.1.1.1",
      "domains": ["geosite:geolocation-!cn"]
    }
  ]
}
```

**Comment by IceCodeNew** [comment]
> 如果 geosite 里变成 full 匹配的话容易让人误解。

我觉得很有道理，那现在改进的方向就是从上游 v2fly/domain-list-community 找出源自 dnsmasq-china-list 的记录，然后把它们中带有的 `full:` 前缀删掉咯？
@IrineSistiana

**Comment by Loyalsoldier** [comment]
@IceCodeNew 

v2fly/domain-list-community 的 apple 和 google 去掉 `full:` 的话，同样会有问题：`domain:` 规则的匹配逻辑为匹配越多域名子串的规则，优先级越高。

```json
"dns": {
  "servers": [
    {
      "address": "114.114.114.114",
      "domains": ["geosite:apple@cn", "geosite:google@cn"]
    },
    {
      "address": "1.1.1.1",
      "domains": ["geosite:geolocation-!cn"]
    }
  ]
}
```

**Comment by IrineSistiana** [comment]
> > 如果 geosite 里变成 full 匹配的话容易让人误解。
> 
> 我觉得很有道理，那现在改进的方向就是从上游 v2fly/domain-list-community 找出源自 dnsmasq-china-list 的记录，然后把它们中带有的 `full:` 前缀删掉咯？ @IrineSistiana

也许我没表述清除....不需要去改 v2fly/domain-list-community  域名。只是改 geosite:apple-cn，geosite:google-cn 里的数据。

我开这个issue是因为看见 README.md 里

```
geosite.dat
基于 @v2fly/domain-list-community/data 数据，通过仓库 @Loyalsoldier/domain-list-custom 生成
加入大量中国大陆域名、Apple 域名和 Google 域名：
@felixonmars/dnsmasq-china-list/accelerated-domains.china.conf 加入到 geosite:cn 类别中
@felixonmars/dnsmasq-china-list/apple.china.conf 加入到 geosite:geolocation-!cn 类别中（如希望本文件中的 Apple 域名直连，请参考下面 geosite 的 Routing 配置方式）
@felixonmars/dnsmasq-china-list/google.china.conf 加入到 geosite:geolocation-!cn 类别中（如希望本文件中的 Google 域名直连，请参考下面 geosite 的 Routing 配置方式）

...

跟 V2Ray 官方 geosite.dat 配置方式相同。相比官方 geosite.dat 文件，本项目特有的类别：
geosite:apple-cn：包含 @felixonmars/dnsmasq-china-list/apple.china.conf 文件里的域名，供希望 Apple 域名直连（不走代理）的用户使用。
geosite:google-cn：包含 @felixonmars/dnsmasq-china-list/google.china.conf 文件里的域名，供希望 Google 域名直连（不走代理）的用户使用。
```

accelerated-domains.china.conf 里的域名是以 domain 匹配的方式加进来了。但apple.china.conf和google.china.conf域名却是以full匹配的方式加入的。会造成了误解，因为使用者会认为geosite:apple-cn，geosite:google-cn的域名源自dnsmasq-china-list所以会用domain匹配，然而却没匹配到期望的域名。

https://github.com/IrineSistiana/mosdns-cn/issues/18

所以我建议统一用domain匹配。

**Comment by IceCodeNew** [comment]
> 也许我没表述清楚....不需要去改 v2fly/domain-list-community 域名。只是改 geosite:apple-cn，geosite:google-cn 里的数据。
> 
> accelerated-domains.china.conf 里的域名是以 domain 匹配的方式加进来了。但apple.china.conf和google.china.conf域名却是以full匹配的方式加入的。会造成了误解，因为使用者会认为geosite:apple-cn，geosite:google-cn的域名源自dnsmasq-china-list所以会用domain匹配，然而却没匹配到期望的域名。
> 
> [IrineSistiana/mosdns-cn#18](https://github.com/IrineSistiana/mosdns-cn/issues/18)
> 
> 所以我建议统一用domain匹配。

懂了，那这个 PR 其实修复的方向有问题对吧。你打算另外开一个 PR 来实现这里的建议吗？我实在是被绕得有点晕了

**Comment by IrineSistiana** [comment]
对,PR 有问题。那个 PR 把 v2fly/domain-list-community 的 apple google 也改了，不应该改的.... 当时我看的也晕了.....

**Comment by Loyalsoldier** [comment]
@IrineSistiana 

你第一个 PR 没问题。但是问题在于，这么改了之后，在 V2Ray 中使用上面我提到的 DNS 配置会导致 geosite:apple-cn 和 geosite:google-cn 无法生效，这样就失去了 apple-cn 和 google-cn 列表在本项目中的意义了。

**Comment by Jan20th9e** [comment]
遇到这个问题了，所以现在是采用full匹配和domain都属于两难的局面么，
https://github.com/Loyalsoldier/domain-list-custom/issues/33
