### ISSUE TITLE
想问一下 一般用户是直接把 geoip.dat，geosite.dat 这两个文件下载替换了就可以了是吗？

### ISSUE THREAD

**Issue by H-xiaolong** [Loyalsoldier/v2ray-rules-dat#167]
想问一下 一般用户是直接把 geoip.dat，geosite.dat 这两个文件下载替换了就可以了是吗？
后面的 txt 文件是如何使用呢 
谢谢大佬

**Comment by Loyalsoldier** [comment]
替换，然后写规则。`geoip:cn`、`geosite:cn` 等……

TXT 文件是用来参考的。

**Comment by Eyion** [comment]
> 替换，然后写规则。`geoip:cn`、`geosite:cn` 等……
> 
> TXT 文件是用来参考的。

直接把txt链接扔进自定义规则里了，不知道如何编写。
