### ISSUE TITLE
从28号起，小爱音响只会说“诶”，无法提供任何服务

### ISSUE THREAD

**Issue by o0HalfLife0o** [Loyalsoldier/v2ray-rules-dat#169]
`resolver.msg.xiaomi.net`
经排查，应该是屏蔽了这个域名导致的，删掉后恢复正常

**Comment by Loyalsoldier** [comment]
Fixed by https://github.com/Loyalsoldier/v2ray-rules-dat/commit/0193852119d26dae381b06bbcb690e2ad8d737f5
