### ISSUE TITLE
关于netflix的咨询

### ISSUE THREAD

**Issue by 1887656** [Loyalsoldier/v2ray-rules-dat#173]
关于geoip:netflix,geosite:netflix，不知准确性如何，netflix也会使用到很多cdn节点，包括Amazon等，在geoip:netflix中是否包含进去了呢？

**Comment by 1887656** [comment]
补充下需求是根据域名或ip进行netflix流量分流，如果CDN节点的asn不是netflix的，那么就不会走netflix的分流路径，达不到解锁的目的了。

**Comment by Loyalsoldier** [comment]
geoip:netflix 里只有属于 Netflix ASN 的 IP。Netflix 解锁自行研究
