### ISSUE TITLE
增强版的 geosite:category-ads-all 问题

### ISSUE THREAD

**Issue by 10330384** [Loyalsoldier/v2ray-rules-dat#174]
增强版中的`geosite:category-ads-all`没有包含原版`geosite:category-ads-all`的内容，增强版使用`geosite:category-ads-all`时部分域名没有被屏蔽，如 pangolin-sdk-toutiao.com，仅使用原版dat文件的`geosite:category-ads-all`能够屏蔽。是否考虑合并官方的`ads-all`?
谢谢

**Comment by Loyalsoldier** [comment]
本项目中的 `geosite:category-ads` 接近于官方版的 `geosite:category-ads-all`，所以可以同时使用本项目的 `geosite:category-ads` 和 `geosite:category-ads-all`
