### ISSUE TITLE
从广告类别中移除log.mmstat.com

### ISSUE THREAD

**Issue by LinaChong** [Loyalsoldier/v2ray-rules-dat#181]
在adguard的屏蔽列表中, log.mmstat.com是被允许访问的, 屏蔽此网页后淘宝网页端无法正常确认收货。
![image](https://user-images.githubusercontent.com/74124808/156107726-89d5fc1e-9e72-4d35-8c0d-a1f0b150f5f8.png)

**Comment by Loyalsoldier** [comment]
感谢提醒。请自行添加到白名单。
