### ISSUE TITLE
[建议] 改用 BGP/ASN 数据建立 geoip

### ISSUE THREAD

**Issue by IceCodeNew** [Loyalsoldier/v2ray-rules-dat#19]
我在上游提了这个建议，但其实实话说我觉得上游不见得有人有动力搞这个，所以我想把这个[建议](https://github.com/v2ray/geoip/issues/20)在这里也提一下：

---
引用 [中国运营商IP地址库](https://github.com/gaoyifan/china-operator-ip/) 里高大的话：
> 在国内，BGP/ASN数据分析的商业服务只有一个ipip.net，是目前运营商IP库准确度最高的服务商，我认为没有之一。
…………
但是，目前国内绝大多数IP库都由WHOIS数据库作为基础数据来源。WHOIS数据仅表示某个IP被哪个机构注册，但无从知晓该IP被用在何处，这就导致许多非运营商自己注册的IP地址无法被正确分类。ipip.net是最早开始做BGP/ASN数据分析的公司之一，数据准确性甩其它库几条街。

我自己也在做和 geoip 项目类似的事，上上周无聊检查了一下我用 MaxMind 免费数据库产生的 ipv6 规则的质量，结果抽了 5 条拿去 ipip 检查，3 条 ip 的归属地都显示香港。
我知道这并不一定代表 ipip 对了 MaxMind 错了，但是从原理上来讲确实从 BGP/ASN 数据建立的 geoip 会让我心里舒坦很多。

也许可以考虑把数据来源换成 GitHub 上许多非常成熟的 BGP 数据，例如：
* [(ipv4) 17mon/china_ip_list](https://github.com/17mon/china_ip_list/blob/master/china_ip_list.txt)
* [(ipv4) gaoyifan/china-operator-ip](https://github.com/gaoyifan/china-operator-ip/blob/ip-lists/china.txt)
* [(ipv6) gaoyifan/china-operator-ip](https://github.com/gaoyifan/china-operator-ip/blob/ip-lists/china6.txt)

另外我本人最近试着把 ipip 的免费公开数据和高大的数据合并，所以也许也可以考虑用我这里生成的规则：
* [(ipv4) IceCodeNew/4Share](https://github.com/IceCodeNew/4Share/blob/master/geoip_china/china_ip_list.txt)
---

我完全没接触过 golang，所以我想也许可以想找到一个和我有同样心思的人，然后搭大佬的便车。
我自己去填这个坑的话不知道猴年马月去了——疫情期间，大学很多事都变得麻烦许多，我想恐怕是很难抽出空来了。

**Comment by Loyalsoldier** [comment]
个人认为，本项目中的 V2Ray 客户端配置和 `geosite.dat` 规则文件，足够满足个人日常使用需求。得益于上游项目，本项目 geosite.dat 规则文件囊括了常见的大陆域名和非大陆域名。配合路由规则 `"domainStrategy": "IPIfNonMatch"` 和发起的请求默认走代理这两项配置，绝大部分情况下不需要先进行 DNS 解析，再发起请求，所以也就谈不上 IP 分类准确不准确的问题（因为绝大部分情况下，访问的都是常用域名，少部分软件和服务才会直接使用 IP 地址对外提供服务。）

而且有一个显著的问题是，IPIP.net 的免费数据只有中国大陆 IP 地址数据，而 V2Ray 部分用户有其他国家和地区 IP 地址的使用需求，想要达到 MaxMind 这样的全球各地区覆盖度的话，我猜测只有 IPIP.net 付费项目才能办到。所以这个提议似乎不太现实。

**Comment by IceCodeNew** [comment]
> 个人认为，本项目中的 V2Ray 客户端配置和 `geosite.dat` 规则文件，足够满足个人日常使用需求。得益于上游项目，本项目 geosite.dat 规则文件囊括了常见的大陆域名和非大陆域名。配合路由规则 `"domainStrategy": "IPIfNonMatch"` 和发起的请求默认走代理这两项配置，绝大部分情况下不需要先进行 DNS 解析，再发起请求，所以也就谈不上 IP 分类准确不准确的问题（因为绝大部分情况下，访问的都是常用域名，少部分软件和服务才会直接使用 IP 地址对外提供服务。）

geoip 不只是用来分流，在我的配置文件里有这样一段：
```
  "dns": {
    "servers": [{
        "address": "https+local://dns.alidns.com/dns-query",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      "localhost"
    ]
  },
```
所以 geoip 的准确性对我来说非常重要。

> 而且有一个显著的问题是，IPIP.net 的免费数据只有中国大陆 IP 地址数据，而 V2Ray 部分用户有其他国家和地区 IP 地址的使用需求，想要达到 MaxMind 这样的全球各地区覆盖度的话，我猜测只有 IPIP.net 付费项目才能办到。所以这个提议似乎不太现实。

你说的很有道理，但是我看 main.go 文件好像也没看到有利用到 中国以外国家的 ip 数据的代码啊？

**Comment by Loyalsoldier** [comment]
MaxMind 免费 IP 库里囊括了所有国家和地区的 IP 地址。V2Ray 配置千千万，永远没有银弹。

**Comment by IceCodeNew** [comment]
嗯，我明白了。
也许可以等以后有空了学学 golang 看能不能自己 fork 一个项目下来专门对 geoip:cn 部分做特殊处理吧。

不然这个问题确实不是换一下数据源就可以解决的问题，坑好大啊。

**Comment by Loyalsoldier** [comment]
这个项目已替换掉了 `CN` 的 IPv4 地址：https://github.com/Loyalsoldier/geoip

**Comment by Loyalsoldier** [comment]
本项目中的 `geoip.dat` 也已经把 `CN` IPv4 CIDR 替换成 IPIP.net 的免费 CN IPv4 CIDR.

**Comment by IceCodeNew** [comment]
> 这个项目已替换掉了 `CN` 的 IPv4 地址：[Loyalsoldier/geoip](https://github.com/Loyalsoldier/geoip)

感谢您！辛苦了~

**Comment by jiangjiangflies** [comment]
> MaxMind 免费 IP 库里囊括了所有国家和地区的 IP 地址。V2Ray 配置千千万，永远没有银弹。
> 
> 路由配置还可以这样用：
> 
> ```
> {
>     "type": "field",
>     "outboundTag": "Proxy",
>     "ip": [
>       "geoip:us",
>       "geoip:uk",
>       "geoip:au"
>     ]
> }
> ```

请问一下，哪个geoip.dat文件支持这样写呢？我配置了geoip:uk，结果出错了。failed to load geoip: uk > infra/conf/geodata/standard: country not found in geoip.dat: uk
