### ISSUE TITLE
app/dispatcher: non existing outTag: proxy   不存在的 outTag：代理

### ISSUE THREAD

**Issue by glenlau228** [Loyalsoldier/v2ray-rules-dat#198]
提示  不存在的 outTag：代理

2022/05/09 16:47:02 [Warning] [2823035323] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:03 [Warning] [222020078] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:03 [Warning] [2902163893] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:07 [Warning] [49535479] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:10 [Warning] [4074066378] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:10 [Warning] [377303969] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:20 [Warning] [2731661718] app/dispatcher: non existing outTag: proxy
2022/05/09 16:47:41 [Warning] [1746480002] app/dispatcher: non existing outTag: proxy
2022/05/09 16:48:17 [Warning] [2187917450] app/dispatcher: non existing outTag: proxy
2022/05/09 16:48:42 [Warning] [3931158776] app/dispatcher: non existing outTag: proxy
2022/05/09 16:48:45 [Warning] [718034023] app/dispatcher: non existing outTag: proxy
2022/05/09 16:49:12 [Warning] [2783102275] app/dispatcher: non existing outTag: proxy
2022/05/09 16:49:12 [Warning] [2776573630] app/dispatcher: non existing outTag: proxy
2022/05/09 16:49:12 [Warning] [347989985] app/dispatcher: non existing outTag: proxy
2022/05/09 16:49:18 [Warning] [4196742702] app/dispatcher: non existing outTag: proxy
2022/05/09 16:49:42 [Warning] [2391452099] app/dispatcher: non existing outTag: proxy
2022/05/09 16:49:46 [Warning] [2006682462] app/dispatcher: non existing outTag: proxy

**Comment by Loyalsoldier** [comment]
增加一个叫 Proxy 的 outbound
