### ISSUE TITLE
geosite:speedtest

### ISSUE THREAD

**Issue by rendaa** [Loyalsoldier/v2ray-rules-dat#20]
我的config.json中，routing rules部分有一行引用了"geosite:speedtest"（应该是v2rayN的Core路由设置界面里的一键设置按钮自动添加的），但使用4月10日的geosite.dat就会导致报错，换回之前3月31日的旧版就无此问题。

**Comment by Loyalsoldier** [comment]
上游项目已经删除了 speedtest 这个分类，在配置文件中删除 geosite:speedtest 即可

**Comment by rendaa** [comment]
谢谢回复

**Comment by Loyalsoldier** [comment]
上游 https://github.com/v2ray/domain-list-community/commit/47bcdec0fdb01c7e7e0fdc8f60fd6d2d3842fa61 重新添加了 `geosite:speedtest` 分类

**Comment by rendaa** [comment]
收到，谢谢！
已下载最新更新，使用正常。
