### ISSUE TITLE
geosite的类别是否有清单可供查询？

### ISSUE THREAD

**Issue by peaksunhuang** [Loyalsoldier/v2ray-rules-dat#201]
另外geosite类别的定义是否可以给个说明，比如geosite:cn是否指在国内的所有域名？

**Comment by Loyalsoldier** [comment]
README 里说的不是很清楚吗

**Comment by Xun66** [comment]
又读了一下readme，确认清单其实就是readme里的domain-list-community

https://github.com/v2fly/domain-list-community/tree/master/data
