### ISSUE TITLE
携程相关域名 (+.ctrip.com) 被包含在category-ads-all中

### ISSUE THREAD

**Issue by jam3ternal** [Loyalsoldier/v2ray-rules-dat#204]
在上游v2fly/domain-list-community中提出issue后得到[反馈](https://github.com/v2fly/domain-list-community/issues/976#issuecomment-1168697980)

**Comment by Loyalsoldier** [comment]
已修复，下次构建会生效：https://github.com/Loyalsoldier/v2ray-rules-dat/commit/9780cff17b6ebcbf2cd1c9a8a1183fe6c0b6171e
