### ISSUE TITLE
部分域名未被屏蔽卻被加入gfw與greatfire

### ISSUE THREAD

**Issue by rootmelo92118** [Loyalsoldier/v2ray-rules-dat#205]
gstatic.com 在中國大陸被屏蔽加入列表可以理解，但旗下子域名例如www.gstatic.com在大陸地區可以直連，是否需要進行特殊處理？

**Comment by Loyalsoldier** [comment]
geosite:gfw 源于 gfwlist，建议去上游提 issue。
geosite:greatfire 源于 greatfire analyzer，不太好处理。
