### ISSUE TITLE
如何测试某个域名或ip属于哪个分区/类别？

### ISSUE THREAD

**Issue by wanzhiyu** [Loyalsoldier/v2ray-rules-dat#206]
比如使用了geosite.dat和geoip.dat文件之后，我想知道cloudflare.com和8.8.8.8是属于国内还是国外？有没有办法直接用命令做测试？

PS：看v2ray日志的方式是可以的，但是太低效了，而且也看不到属于哪个分区/类别。

**Comment by Loyalsoldier** [comment]
目前没有相关命令行。也许以后会有。
