### ISSUE TITLE
Telegraph域名被误加入广告列表

### ISSUE THREAD

**Issue by Blink1024** [Loyalsoldier/v2ray-rules-dat#208]
`telegra.ph`不应该被屏蔽
<https://zh.wikipedia.org/wiki/Telegraph>

此域名出现在[@DanPollock/hosts](https://someonewhocares.org/hosts/)中

**Comment by Loyalsoldier** [comment]
已移除 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/944333b0aba5b4c74d7150c58b5aaee16a4f0a24
