### ISSUE TITLE
【列表更新】希望增加以下直连地址

### ISSUE THREAD

**Issue by rainpenber** [Loyalsoldier/v2ray-rules-dat#210]
## Direct List
> 以下地址是自己在使用过程中体验对比，希望能加入直连列表的地址（在白名单模式下会被走代理）
- 888ban.com,
- 8x6x.com,
- makeflow.com,
- natapp1.cc,
- oneplus.cn,
- oneplus.com,
- yueliu.cn,
- yueliu.cloud,
- getrolan.com,
- yuelili.com,
- mgzyfx.com,
- aplaybox.com,
- lookae.com,
- musetransfer.com,
- pixcall.com,
- ifonts.com

## Mis-categoried
> 以下地址被误识别为广告（可能某种程度是广告，但是已经影响干扰到正常工作）
- misterhorse.postaffiliatepro.com,

**Comment by Loyalsoldier** [comment]
建议自行添加到自己的规则中。
