### ISSUE TITLE
域名匹配方法应该默认为`domain:`，即子域名匹配

### ISSUE THREAD

**Issue by willyywt** [Loyalsoldier/v2ray-rules-dat#211]
[v2fly RuleObject](https://www.v2fly.org/config/routing.html#ruleobject)文档里面说纯字符串匹配域名的**任意部分**，比如`ntent.com`匹配`raw.githubusercontent.com`，`sina.com`匹配`sina.company`，但是我认为绝大部分情况下都应该用子域名匹配，纯字符串匹配会产生难以预期的错误规则

域名整理成v2fly可以识别的格式的时候，应该在绝大部分域名前面加入`domain:`以让规则变成子域名匹配

**Comment by Loyalsoldier** [comment]
默认就是子域名匹配啊，而不是 keyword 匹配

**Comment by willyywt** [comment]
默认不是子域名匹配吧。。

**Comment by willyywt** [comment]
> 默认就是子域名匹配啊，而不是 keyword 匹配

我在v2ray 4.45.2上面测试出来，不加前缀`domain:`会导致`raw.githubusercontent.com`被屏蔽
