### ISSUE TITLE
对 domain-list-community/data/google CN 部分的处理不正确

### ISSUE THREAD

**Issue by legendtang** [Loyalsoldier/v2ray-rules-dat#215]
例如

https://github.com/v2fly/domain-list-community/blob/4d5df1dd79600f1fbdd04a8fc9428845a3b19d59/data/google#L86

和

https://github.com/v2fly/domain-list-community/blob/4d5df1dd79600f1fbdd04a8fc9428845a3b19d59/data/google#L391

及其余 63 处的 Google CN 域名需要排除，目前观测到应用此规则无法正确处理 Google CN 域名，

https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt

里面还是包括 google.cn 等

**Comment by Loyalsoldier** [comment]
建议把 Google 相关域名都进行代理即可。

**Comment by ITJesse** [comment]
确实 google cn 域名不应该被代理。会导致很多资源访问缓慢。

**Comment by Loyalsoldier** [comment]
设置 `geosite:google-cn` 为直连就可以直连啊
