### ISSUE TITLE
将apple.txt里的内容放到proxy.txt里，action出来的proxy-list.txt却找不到

### ISSUE THREAD

**Issue by GeorgeRudd** [Loyalsoldier/v2ray-rules-dat#216]
试了一下，随便写了一个域名进去proxy.txt，action出来proxy-list.txt是有的
但是把整个apple.txt文件复制proxy.txt进去就不行 https://github.com/v2fly/domain-list-community/blob/release/apple.txt

本意是想让Apple类别所有带 @ cn 的域名也加到geosite:geolocation-!cn里

好像只要是 @ cn 属性的域名，就算加到proxy.txt也没用，比如apple.com.cn

**Comment by Loyalsoldier** [comment]
在 `geosite:geolocation-!cn` 前（上）面添加一条规则即可：`geosite:apple` 走代理。
