### ISSUE TITLE
分类的调整请慎重，调整后发布时最好说明一下

### ISSUE THREAD

**Issue by rendaa** [Loyalsoldier/v2ray-rules-dat#219]
geosite:gfw等这样的分类，几天前的发布版还包括，过几天就突然没了，再过一阵儿又恢复了。config.json里引用了不存在的分类的话，v2ray核心启动的时候会报错，根本启动不了，对把几乎向外网的所有数据都转发给v2ray、由v2ray选择路由规则的透明代理的实现方式来说，这会弄得连网都上不了……

还请维护geo files的朋友们调整时慎重一些，毕竟大量的用户会有不同的需求，一点细微的调整都可能有或多或少不太希望出现的影响。

在此顺便感谢各位帮助维护这个项目的朋友们的贡献！

**Comment by Loyalsoldier** [comment]
最近没改动
