### ISSUE TITLE
translate.googleapis.com这个域名现在是不是可以改成PROXY的了

### ISSUE THREAD

**Issue by chensimmons** [Loyalsoldier/v2ray-rules-dat#229]
主要是最近一个月在Chrome上用网页翻译时，经常失败，白名单模式，看了看v2ray日志，是因为translate.googleapis.com这个域名走了直连，如果走代理就正常了，今天看到新闻，谷歌翻译退出中国了，translate.google.cn这个域名不能用了，所以想问问translate.googleapis.com是不是可以改成PROXY的了

**Comment by Loyalsoldier** [comment]
更新一下 geosite.dat
