### ISSUE TITLE
a-i-ad.com与bdtj.tagtic.cn 望移除

### ISSUE THREAD

**Issue by KagamigawaMeguri** [Loyalsoldier/v2ray-rules-dat#23]
a-i-ad.com是DMM的网站，加入后容易导致游戏点不开……
bdtj.tagtic.cn 是nga的统计网站，会导致点击帖子无法正常加载

**Comment by Loyalsoldier** [comment]
`bdtj.tagtic.cn` 已移除。`a-i-ad.com` 是上游项目屏蔽的，本项目无法处理，已尝试给上游项目提交 Pull Request.

**Comment by Loyalsoldier** [comment]
上游已解决问题。
