### ISSUE TITLE
清华的教工邮箱域名被列进了广告域名列表

### ISSUE THREAD

**Issue by aod321** [Loyalsoldier/v2ray-rules-dat#231]
为何清华的教工邮箱地址mail.tsinghua.edu.cn在reject.txt里呢? 怎么样提案可以去掉它？

**Comment by Loyalsoldier** [comment]
已修复：https://github.com/Loyalsoldier/v2ray-rules-dat/commit/a9e8840d826b78d9ca0c5a9653b7c8b94aca9f5c
