### ISSUE TITLE
请在cn组收录 www.swok.cn  这是电信测速软件的下载地址

### ISSUE THREAD

**Issue by yanghonghao6789** [Loyalsoldier/v2ray-rules-dat#233]
不收录时报dns_probe_finished_nxdomain

手动在直连加入 就可以正常打开页面

**Comment by Loyalsoldier** [comment]
`cn` 域名默认是直连的

**Comment by yanghonghao6789** [comment]
> 

可是什么也不加 网页直接打不开，加了才可以打开。我用的passwall  在adg里报SERVFAIL
