### ISSUE TITLE
geosite:cn includes google-play-store domain

### ISSUE THREAD

**Issue by wanqx** [Loyalsoldier/v2ray-rules-dat#235]
Server settings: 
{
    "type": "field",
    "domain": ["geosite:cn"],
    "outboundTag": "block"
 }
This setting makes my phone fail to download apps in google play store. I have tested several times.
geosite:cn这个设置会阻止google play store里更新应用，在一次更新后发现了这个问题，猜测是geosite:cn包含了谷歌商店下载的相关域名，麻烦看一下是不是这样。

目前通过这种办法解决
        {
        "type": "field",
        "domain": ["geosite:google"],
        "outboundTag": "direct"
        },
        {
          "type": "field",
          "ip": ["geoip:private", "geoip:cn"],
          "outboundTag": "block"
        },
        {
        "type": "field",
        "domain": ["geosite:category-ads-all", "geosite:cn"],
        "outboundTag": "block"
        }

**Comment by Loyalsoldier** [comment]
把 `geosite:google` 设置为代理即可
