### ISSUE TITLE
direct communicate all top level domain like .uk

### ISSUE THREAD

**Issue by unknown-qp** [Loyalsoldier/v2ray-rules-dat#236]
How can I set all .uk domains to communicate directly in v2ray routing section (server) ? Do I need Regex? Thank you for your advice

**Comment by Loyalsoldier** [comment]
Add a routing rule for V2Ray v4:

```
{
  "type": "field",
  "outboundTag": "Direct",
  "domain": ["domain:uk"]
}
```

**Comment by unknown-qp** [comment]
hi again @Loyalsoldier, thanks for answer, im test this code, but unfortunately it doesn't work. 
This is my current setup :

{
    "api": {
      "services": [
        "HandlerService",
        "LoggerService",
        "StatsService"
      ],
      "tag": "api"
    },
    "dns": {
      "hosts": {
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4"
        ],
        "dns.pub": "119.29.29.29",
        "dns.alidns.com": "223.5.5.5"
      },
      "servers": [
        {
          "address": "https://1.1.1.1/dns-query",
          "domains": [
            "geosite:geolocation-!cn",
            "geosite:google@cn"
          ],
          "expectIPs": [
            "geoip:!cn"
          ]
        },
        "1.1.1.1",
        {
          "address": "localhost",
          "skipFallback": true
        }
      ],
      "queryStrategy": "UseIP"
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 62789,
        "protocol": "dokodemo-door",
        "settings": {
          "address": "127.0.0.1"
        },
        "tag": "api"
      }
    ],
    "outbounds": [
      {
        "protocol": "freedom",
        "settings": {}
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "blocked"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "blockedByIp"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "blockedByDomain"
      }
    ],
    "policy": {
      "levels": {
        "0": {
          "handshake": 4,
          "connIdle": 300,
          "uplinkOnly": 2,
          "downlinkOnly": 5,
          "statsUserUplink": false,
          "statsUserDownlink": false,
          "bufferSize": 4
        }
      },
      "system": {
        "statsInboundDownlink": true,
        "statsInboundUplink": true
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "domainMatcher": "hybrid",
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        },
        {
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "outboundTag": "blockedByIp",
          "type": "field"
        },
        {
          "type": "field",
          "domain": [
            "geosite:category-ads-all",
            "geosite:geolocation-cn",
            "geosite:microsoft"
          ],
          "outboundTag": "blockedByDomain"
        },
        {
          "outboundTag": "blocked",
          "protocol": [
            "bittorrent"
          ],
          "type": "field"
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ]
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "domain": ["domain:uk", "domain:af", "domain:ir"]
        }
      ]
    },
    "stats": {}
  }

**Comment by unknown-qp** [comment]
> Add a routing rule for V2Ray v4:
> 
> ```
> {
>   "type": "field",
>   "outboundTag": "Direct",
>   "domain": ["domain:uk"]
> }
> ```

hi again @Loyalsoldier, thanks for answer, im test this code, but unfortunately it doesn't work.
This is my current setup :

```
{
    "api": {
      "services": [
        "HandlerService",
        "LoggerService",
        "StatsService"
      ],
      "tag": "api"
    },
    "dns": {
      "hosts": {
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4"
        ],
        "dns.pub": "119.29.29.29",
        "dns.alidns.com": "223.5.5.5"
      },
      "servers": [
        {
          "address": "https://1.1.1.1/dns-query",
          "domains": [
            "geosite:geolocation-!cn",
            "geosite:google@cn"
          ],
          "expectIPs": [
            "geoip:!cn"
          ]
        },
        "1.1.1.1",
        {
          "address": "localhost",
          "skipFallback": true
        }
      ],
      "queryStrategy": "UseIP"
    },
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 62789,
        "protocol": "dokodemo-door",
        "settings": {
          "address": "127.0.0.1"
        },
        "tag": "api"
      }
    ],
    "outbounds": [
      {
        "protocol": "freedom",
        "settings": {}
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "blocked"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "blockedByIp"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "blockedByDomain"
      }
    ],
    "policy": {
      "levels": {
        "0": {
          "handshake": 4,
          "connIdle": 300,
          "uplinkOnly": 2,
          "downlinkOnly": 5,
          "statsUserUplink": false,
          "statsUserDownlink": false,
          "bufferSize": 4
        }
      },
      "system": {
        "statsInboundDownlink": true,
        "statsInboundUplink": true
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "domainMatcher": "hybrid",
      "rules": [
        {
          "inboundTag": [
            "api"
          ],
          "outboundTag": "api",
          "type": "field"
        },
        {
          "ip": [
            "geoip:cn",
            "geoip:private"
          ],
          "outboundTag": "blockedByIp",
          "type": "field"
        },
        {
          "type": "field",
          "domain": [
            "geosite:category-ads-all",
            "geosite:geolocation-cn",
            "geosite:microsoft"
          ],
          "outboundTag": "blockedByDomain"
        },
        {
          "outboundTag": "blocked",
          "protocol": [
            "bittorrent"
          ],
          "type": "field"
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": [
            "geosite:cn"
          ]
        },
        {
          "type": "field",
          "outboundTag": "direct",
          "ip": [
            "geoip:private",
            "geoip:cn"
          ]
        },
        {
          "type": "field",
          "outboundTag": "Direct",
          "domain": ["domain:uk", "domain:af", "domain:ir"]
        }
      ]
    },
    "stats": {}
  }
```
