### ISSUE TITLE
被误判为国外的国内IP

### ISSUE THREAD

**Issue by redstoneleo** [Loyalsoldier/v2ray-rules-dat#238]
这是个国内ip应该是被误判为国外的了，请检查一下是否如此
112.45.35.242
112.45.35.241
112.45.35.240
另外，我发现了个貌似可以的国内IP项目也许对本项目有帮助吧
 https://github.com/Hackl0us/GeoIP2-CN

**Comment by yanghonghao6789** [comment]
这个规则485934条数据，比openwrt的ssr里默认配置的clang.cn多好多才八千多条   我给ssr用上了

**Comment by LawssssCat** [comment]
同样的，配置 pac 后，（bilibili、京东、微信小程序 ）都要断了 代理才能访问

**Comment by redstoneleo** [comment]
> 同样的，配置 pac 后，（bilibili、京东、微信小程序 ）都要断了 代理才能访问

我也碰到了同样的情况。你用的是什么软件配置 pac？

**Comment by LawssssCat** [comment]
> 你用的是什么软件配置 pac？

win10、android 自带的”自动配置“设置

**Comment by redstoneleo** [comment]
@LawssssCat 你应该是用的这种方法设置pac吧，https://juejin.cn/post/6844903567204024328，不同的wifi都要设置的话感觉不方便。这里提到的APP似乎更方便吧https://www.v2ex.com/t/228115

**Comment by redstoneleo** [comment]
经过我的测试，目前发现最准的还是这个 https://github.com/lionsoul2014/ip2region

**Comment by Loyalsoldier** [comment]
已添加数据源 https://github.com/gaoyifan/china-operator-ip

**Comment by redstoneleo** [comment]
> 已添加数据源 https://github.com/gaoyifan/china-operator-ip

非常感谢大佬！
