### ISSUE TITLE
dnsmasq-china-list里面的apple和google应该是可直接访问的？

### ISSUE THREAD

**Issue by bash99** [Loyalsoldier/v2ray-rules-dat#24]
比如 https://www.gstatic.com/ 
可以解析到正确的ip并且国内访问 

不应该放到 !cn 里面？

**Comment by Loyalsoldier** [comment]
是可以访问。但是本项目倾向于将 Apple 和 Google 所有域名流量都走代理。如果希望直连，参考 https://github.com/Loyalsoldier/v2ray-rules-dat/issues/21#issuecomment-612713449
