### ISSUE TITLE
[建议] 可以打包在一起吗

### ISSUE THREAD

**Issue by CALMorACT** [Loyalsoldier/v2ray-rules-dat#25]
因为打算使用scoop来自动加入更新, 但是scoop的autoupdate不支持两个文件一起
所以建议两个放在一个压缩包中, 同时给出sha256

**Comment by Loyalsoldier** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat/commit/838b85e50ae4f10a34a397e90d04084cd0c1ed50 已生成打包文件 `rules.zip` 和验证文件 `rules.zip.sha256sum`

**Comment by CALMorACT** [comment]
谢谢大佬
