### ISSUE TITLE
域名不匹配`category-ads-all`

### ISSUE THREAD

**Issue by kabegoe** [Loyalsoldier/v2ray-rules-dat#252]
没有完全测试，但发现*v2fly/domain-list-community*下*category-ads*的域名，例如`adx.36kr.com`([Link](https://github.com/v2fly/domain-list-community/blob/master/data/category-ads#L100-L101))，只会匹配*category-ads*但不匹配***category-ads-all***。

> ***category-ads-all***中有`include:category-ads`([Link](https://github.com/v2fly/domain-list-community/blob/master/data/category-ads-all#L29))。

*v2fly/domain-list-community*以及您的*Loyalsoldier/domain-list-custom*就没有这个问题。

我也阅读了您这个仓库的README，好像没有关于从***category-ads-all***中删减域名的描述。请问是有bug还是我理解有误？

测试环境：`Xray 1.7.0 (Xray, Penetrates Everything.) Custom (go1.19.4 linux/amd64)`

**Comment by Loyalsoldier** [comment]
本项目中的广告和隐私追踪相关的域名并不源于 v2fly/domain-list-community

**Comment by kabegoe** [comment]
谢谢您的解答！
