### ISSUE TITLE
是否可以添加steam@cn对下载时的支持

### ISSUE THREAD

**Issue by ShiinaRinne** [Loyalsoldier/v2ray-rules-dat#254]
- 不使用代理的速度
![image](https://user-images.githubusercontent.com/45081750/213922424-9ec72046-cb61-4e60-a00d-f4ca50d683e9.png)

- 开启代理之后的速度(使用`steam@cn`, 同时设置`steamcontent.com`为直连)
![image](https://user-images.githubusercontent.com/45081750/213922434-6879a6bd-4c7e-4ffb-96bf-617dd1261b64.png)
![image](https://user-images.githubusercontent.com/45081750/213922285-3c4d4523-3cc3-42b5-acab-5432d706d6ae.png)
可以看到, 对`steamcontent.com`下的每个分块, 都通过直连的方式进行下载, 这不会消耗服务器的流量, 但是下载服务器却会因为代理的原因, 变成`tyo`, `sgp`等, 对下载速度造成了严重影响.

~~可能是因为我总是开机自启+常驻全局, 所以才会被这个问题影响xd~~

猜测是在登录时有某个api获取了ip/位置/延迟信息, 之后选择更近的服务器进行下载. 
现在我是将`steamserver.net`设置为直连来解决这个问题, 这样在`开代理-> 开steam-> 下载`时候也会通过国内最近服务器下载, 省去关闭代理与重启steam的时间, 会更加方便
但暂时不清楚是否会造成其他影响, 不确定是否可以标记为`@cn`
https://github.com/Loyalsoldier/v2ray-rules-dat/issues/254#issuecomment-1407586061

**Comment by yjosx** [comment]
我也遇到了相同的问题，请问解决了吗？

**Comment by ShiinaRinne** [comment]
> 我也遇到了相同的问题，请问解决了吗？

在我现在临时解决的方案中, 只需要将`steamserver.net`设置为直连即可

目前不知道具体有哪些服务是通过这个domain的, 
单独对`ext4-hkg1.steamserver.net` `ext2-tyo2.steamserver.net`等二级域名设置可能会更不容易出问题

社区, 商店和创意工坊等不用这个, 不会受到影响
![O$(~{8J$G{T_FSUU5`$4QHT](https://user-images.githubusercontent.com/45081750/215311042-ec46fdc0-e056-4741-ab96-e6be847f0478.png)
![image](https://user-images.githubusercontent.com/45081750/215311066-0cf9afba-ef2b-4278-8611-20ee8c9a47f8.png)
