### ISSUE TITLE
可以更新一下Greatfire Analyzer列表吗？

### ISSUE THREAD

**Issue by PaTTeeL** [Loyalsoldier/v2ray-rules-dat#257]
看了一下 @Loyalsoldier/cn-blocked-domain ，貌似很久没更新了，可以更新一下吗？
部分网站貌似已经不在列表里了。

**Comment by lychichem** [comment]
想报告amd也没被墙啊怎么就进greatfire列表了，希望去掉

**Comment by PaTTeeL** [comment]
嗯嗯，我也是因为eu.org进了greatfire列表，去https://zh.greatfire.org/analyzer查了一下发现是0%，以为是没更新，仔细看了本项目的action才发现已经每天实时拉取了，后来发现gfwlist也把eu.org放进了列表，就不知道怎么搞了……
