### ISSUE TITLE
d.ifengimg.com凤凰网视频的预览图全被屏蔽了

### ISSUE THREAD

**Issue by o0HalfLife0o** [Loyalsoldier/v2ray-rules-dat#26]
https://v.ifeng.com/

**Comment by Loyalsoldier** [comment]
已从广告域名列表中去除域名 `d.ifengimg.com`，请下载最新版 `geosite.dat`

**Comment by o0HalfLife0o** [comment]
icons.mydrivers.com快科技的各种图标也被误屏蔽了

**Comment by Loyalsoldier** [comment]
> icons.mydrivers.com[快科技](https://www.mydrivers.com/)的各种图标也被误屏蔽了

已添加到移除列表。等待明天新版 `geosite.dat` 更新

**Comment by o0HalfLife0o** [comment]
`pingjs.qq.com`
会导致部分网站、app异常，比如京东金融app中我的资产里所有项目都点不了，接触屏蔽后恢复

**Comment by Loyalsoldier** [comment]
> `pingjs.qq.com`
> 会导致部分网站、app异常，比如京东金融app中我的资产里所有项目都点不了，接触屏蔽后恢复

8232c86300e5e2e01badf09cd25427a27b06e2c9 已移除。
