### ISSUE TITLE
是否可将google.cn和gvt1.com加入google-cn.txt？

### ISSUE THREAD

**Issue by im-Kalix** [Loyalsoldier/v2ray-rules-dat#263]
关于`*.gvt1.com`的详细信息，参见https://github.com/gfwlist/gfwlist/issues/2362 和https://github.com/felixonmars/dnsmasq-china-list/issues/370

**Comment by Loyalsoldier** [comment]
google-cn.txt 的上游项目是 @felixonmars/dnsmasq-china-list ，跟随上游变更。

**Comment by im-Kalix** [comment]
> google-cn.txt 的上游项目是 @felixonmars/dnsmasq-china-list ，跟随上游变更。

此上游项目的描述中有这样一段话：
`Please don't add subdomains if the top domain is already in the list. This includes all .cn domains which are already matched by the /cn/ rule.`
`如果顶级域已经在列表中，请不要添加子域。这包括所有已经与/cn/规则匹配的.cn域。`

所以此上游项目不会添加google.cn，但是这条规则与此项目的设计并不兼容。

**Comment by Loyalsoldier** [comment]
google-cn.txt 的上游文件是 https://github.com/felixonmars/dnsmasq-china-list/blob/master/google.china.conf ，不受 /cn/ 规则的影响。

**Comment by im-Kalix** [comment]
但是在这一条Issue里作者就拿这个作论据了 https://github.com/felixonmars/dnsmasq-china-list/issues/394
