### ISSUE TITLE
Apple国外的部分域名被添加到geosite:cn了

### ISSUE THREAD

**Issue by lucky-beans** [Loyalsoldier/v2ray-rules-dat#266]
有相当一部分Apple.com国外相关域名被添加到geosite:cn了。比如国内苹果服务使用的是apple.com.cn和icloud.com.cn，那么这两个才是应该被添加到geosite:cn的，而不是国外使用的apple.com和icloud.com。
v2fly社区的原版geosite没这问题。

**Comment by Loyalsoldier** [comment]
需要细化 Apple 相关域名的路由，请添加 `geosite:apple` 或 `geosite:apple@cn` 的路由规则。

**Comment by kdurov** [comment]
能否修改现有cn分类成原版一样呢？即去掉 apple.com 等全球通用的域名。
如果需要在国内用分流可以手动添加 geosite:apple-cn 到direct分流。

毕竟 apple.com mzstatic.com icloud.com 还有一些 google的gstatic并不是cn站，geoip也不是cn。

**Comment by Loyalsoldier** [comment]
@kdurov  众口难调，请自行处理

**Comment by kdurov** [comment]
不过现在这情况分类并不合理吧。
Apple Google 怎么说都不应该放 cn 分类吧，当然在 geolocation-!cn 里是没问题的。
只有在国内用的情况，考虑到 CDN 问题让这些直连加速而已。
难道  geosite:apple-cn  geosite:google-cn 的诞生不就是为了把这些域名从 geolocation-!cn 里面细分出来么？

如果说没法改的话，能否考虑添加分类呢？比如说 geosite:cn-only 这样的不包括国外站的国内CDN域名，geosite:cn-extra 包含真cn站+国外能直连加速域名？
