### ISSUE TITLE
direct-list.txt 中有重复（冲突）项

### ISSUE THREAD

**Issue by ycmmonkey** [Loyalsoldier/v2ray-rules-dat#269]
比如行
bg.v4.a.dl.ws.microsoft.com
bg4.v4.a.dl.ws.microsoft.com
与
full:bg.v4.a.dl.ws.microsoft.com
full:bg4.v4.a.dl.ws.microsoft.com

还有其他类似冲突项，看上去都是微软的域名

**Comment by ycmmonkey** [comment]
> 比如行 bg.v4.a.dl.ws.microsoft.com bg4.v4.a.dl.ws.microsoft.com 与 full:bg.v4.a.dl.ws.microsoft.com full:bg4.v4.a.dl.ws.microsoft.com
> 
> 还有其他类似冲突项，看上去都是微软的域名


https://raw.githubusercontent.com/Loyalsoldier/domain-list-custom/release/cn.txt
应该是这个文件中的
full:bg.v4.a.dl.ws.microsoft.com:@cn
full:bg4.v4.a.dl.ws.microsoft.com:@cn
full:cdn.marketplaceimages.windowsphone.com:@cn
full:cn.windowssearch.com:@cn
full:ctldl.windowsupdate.com:@cn
full:developer.microsoft.com:@cn
full:docs.microsoft.com:@cn
full:download.microsoft.com:@cn
full:download.visualstudio.microsoft.com:@cn
full:fs.microsoft.com:@cn
full:msgr.dlservice.microsoft.com:@cn
full:msgruser.dlservice.microsoft.com:@cn
full:officecdn.microsoft.com:@cn
full:qh.dlservice.microsoft.com:@cn
full:sdx.microsoft.com:@cn
full:silverlight.dlservice.microsoft.com:@cn
full:slupdate.dlservice.microsoft.com:@cn
full:storeedgefd.dsx.mp.microsoft.com:@cn
full:wl.dlservice.microsoft.com:@cn
full:wscont1.apps.microsoft.com:@cn
full:wscont2.apps.microsoft.com:@cn
full:xb.dlservice.microsoft.com:@cn
没有与
https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
做好去重

**Comment by Loyalsoldier** [comment]
`full` 规则与普通规则在 V2Ray 中的行为不一致，故意保留 `full` 项。
