### ISSUE TITLE
一个不痛不痒的BUG

### ISSUE THREAD

**Issue by yfw918** [Loyalsoldier/v2ray-rules-dat#286]
把geosite:google-cn放进direct规则后，测试的时候发现列表里第一个网站265.com还是会走代理，开始以为是自己路由顺序不对，后来发现其他网站都能正常直连，只有265.com走代理，不知道是什么原因
![git1](https://user-images.githubusercontent.com/47084648/234600763-d6704c35-1a91-4a51-8930-c9559d178539.png)
![git2](https://user-images.githubusercontent.com/47084648/234600776-f7edd049-8645-411a-8a5b-665b11ee1e94.png)

**Comment by Loyalsoldier** [comment]
`265.com` 刚好也在 `geosite:geolocation-!cn` 里，且代理列表排在前（上）面
