### ISSUE TITLE
geosite:category-ads-all does not affect YouTube and YouTube Music ads

### ISSUE THREAD

**Issue by danialzadrafiee** [Loyalsoldier/v2ray-rules-dat#294]
this is my block list :
geosite:category-ads-all
geosite:category-ads-all
geosite:category-ads
geosite:google-ads
geosite:google@ads
I test it on
sing-box
v2ray
and clash

But it still has no effect on blocking YouTube and YouTube music ads.
I can't figure out where the problem is

**Comment by Loyalsoldier** [comment]
YouTube uses the same domain for video/audio stream and ads. So you cannot block YouTube ads just by domain rejection. 

Instead, use Ad blocker plugin like `uBlock Origin` on Windows, macOS or Linux. Or VPN tools with MITM feature.
