### ISSUE TITLE
xray路由里屏蔽geosite:cn之后Google无法登陆

### ISSUE THREAD

**Issue by soundghost** [Loyalsoldier/v2ray-rules-dat#298]
在xray的路由规则里设置了geosite:cn走block之后，Google无法登陆，但是已经登录后的账户不影响使用（大多数Google服务），但是Google keep也无法加载。

xray开启了访问日志后查看日志，看到ssl.gstatic.com 被阻止。

只要删除geosite:cn之后Google就正常使用了。

**Comment by Loyalsoldier** [comment]
本项目中的 `geosite:cn` 包含 Google 在中国大陆可直连的域名。如果需要屏蔽 cn 域名且保证 Google 域名不被屏蔽，可以在 geosite:cn 规则前（上）面为 geosite:google 设置为走代理或直连。
