### ISSUE TITLE
这里的dat有什么意义吗？

### ISSUE THREAD

**Issue by 1265578519** [Loyalsoldier/v2ray-rules-dat#3]
没看明白有什么作用

**Comment by Loyalsoldier** [comment]
尽可能地让大陆域名直连，让海外域名走代理，免除 DNS 污染的影响，并且对于加入到规则中的走代理的域名不会因为查询 A 和 AAAA DNS 记录而导致 DNS 泄漏。

**Comment by DHJ666** [comment]
> 彻底地让大陆域名直连，让海外域名走代理，免除DNS污染的影响，并且为了加入到规则中的走代理的域名不会因为查询A和AAAA DNS记录而导致DNS泄漏。

大佬您好，我用的pac模式，现在想将一个被墙网址加入代理，该如何实现呢，dat文件我打开是乱嘛，求指点

**Comment by 1265578519** [comment]
@DHJ666 
![image](https://user-images.githubusercontent.com/6442439/74592132-3df50280-5059-11ea-8f42-866d51e99791.png)
根据二楼的解答，，我感觉是这个东西用这个dat，也就是全局模式下然后进行分流

**Comment by Loyalsoldier** [comment]
@DHJ666 
dat 规则文件只适用于全局模式。使用 PAC 模式的话，请根据下面链接里的方法来添加规则：
https://github.com/shadowsocks/ShadowsocksX-NG/issues/333#issuecomment-330725920

**Comment by 1265578519** [comment]
@DHJ666 软件自带，更方便
![image](https://user-images.githubusercontent.com/6442439/74931862-7c087280-541b-11ea-9e33-914e280506bf.png)
