### ISSUE TITLE
可以增加 geoip:chatgpt  吗

### ISSUE THREAD

**Issue by cary-sas** [Loyalsoldier/v2ray-rules-dat#300]
如题

**Comment by Loyalsoldier** [comment]
openai 没有使用独有的 ASN，不能添加。

**Comment by anserme** [comment]
> > openai 没有使用独有的 ASN，不能添加。
> 
> https://github.com/v2fly/domain-list-community/blob/master/data/openai
> 
> 那这个工程里为什么他们在update里又openai相关的更新呢？

这里更新的是域名，不是ip
