### ISSUE TITLE
geoip:private 中包含了公网IP？

### ISSUE THREAD

**Issue by Sheng-Horizon** [Loyalsoldier/v2ray-rules-dat#302]
我在服务端的```config.json```中加入这样一个路由规则：
```json
{
        "type": "field",
        "ip": [
               "geoip:private"
         ],
         "outboundTag": "block"
}
```
然后 ```chat.openai.com``` 就会被直接block掉

**Comment by Loyalsoldier** [comment]
没有

**Comment by KoinuDayo** [comment]
> 我在服务端的`config.json`中加入这样一个路由规则：
> 
> ```json
> {
>         "type": "field",
>         "ip": [
>                "geoip:private"
>          ],
>          "outboundTag": "block"
> }
> ```
> 
> 然后 `chat.openai.com` 就会被直接block掉

可能是你服务器提供商给你dns解锁了内网直达openai
