### ISSUE TITLE
我的自定义规则这样是否正确

### ISSUE THREAD

**Issue by TingTing1990** [Loyalsoldier/v2ray-rules-dat#304]
我的需求：总的来说其实就是大陆和局域网后代理加上苹果直连接（以下这样是纯个人喜欢最终兜底走代理，在手机v2rayNG上使用）

1、下载geoip.dat和geosite.dat文件覆盖

2、自定义代理的网站或IP规则：
geosite:gfw

3、自定义直连的网站或IP规则：
geosite:apple-cn,
geosite:cn,
geoip:cn,
geoip:private

4、预定义规则设置：
全局代理

多谢！

**Comment by Loyalsoldier** [comment]
没啥问题。还可以添加 `geosite:private` 为直连。

**Comment by TingTing1990** [comment]
> 没啥问题。还可以添加 `geosite:private` 为直连。

非常感谢，我想知道里面的域名的匹配规则，比如“direct-list.txt”里的"00.net"是完整匹配还是域名后缀匹配等...

**Comment by TingTing1990** [comment]
> 00.net 匹配 `00.net` 和 `www.00.net`、`abc.00.net`，不匹配 `100.net`

多谢！
