### ISSUE TITLE
Can the examples be updated to work with Xray?

### ISSUE THREAD

**Issue by houmie** [Loyalsoldier/v2ray-rules-dat#307]
Is it possible to update the [examples](https://github.com/Loyalsoldier/v2ray-rules-dat#%E8%87%AA%E7%94%A8-v2ray-v4-%E7%89%88%E6%9C%AC%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%B8%8D%E9%80%82%E7%94%A8%E4%BA%8E-v2ray-v5-%E5%8F%8A%E6%9B%B4%E6%96%B0%E7%9A%84%E7%89%88%E6%9C%AC) to work with Xray?

The examples are very good and comprehensive. but they use an outdated version of V2Ray. Is it possible to adjust them for Xray?

Thanks

**Comment by Loyalsoldier** [comment]
Sorry, you need to read the docs and write your own config. They change a lot and I use neither of them anymore.

Or maybe you should try [Clash](https://github.com/Dreamacro/clash) of which configuration is easier to understand. And I also have a rule project for Clash called [clash-rules](https://github.com/Loyalsoldier/clash-rules) based on this one.
