### ISSUE TITLE
为什么要将geosite:apple-cn和geosite:google-cn加入到geosite:cn中？

### ISSUE THREAD

**Issue by FlyoverMe** [Loyalsoldier/v2ray-rules-dat#309]
您好，我的代理一直在用绕过中国大陆地址（白名单）模式，今天把v2ray自带的域名库换成了这个，发现几乎所有与apple相关的域名都不走代理节点了。检查release分支下的**direct-list.txt**文件，发现`geosite:apple-cn`和`geosite:google-cn`类别的域名都被包含进去了。看了下closed的issue已经有人发现这个问题了，但反馈了又没什么作用。我觉得这样安排并不是很合理，因为`geosite:apple-cn`和`geosite:google-cn`里面的域名只是在中国有CDN节点而已，域名本身并不属于中国域名；并且**README.md**中也没有提到会把`geosite:apple-cn`和`geosite:google-cn`都包含进`geosite:cn`中，按照现在这样的话下面白名单的参考配置中第二个路由规则就有点脱裤子放屁的感觉了。觉得现在这个操作对于我这种流量充足的白名单用户来说不是很友好，希望能不要把`geosite:apple-cn`和`geosite:google-cn`包含在cn中，根据目前的参考配置对代理流量不充足的白名单用户不会有任何影响。愿改进，谢谢！

**Comment by Loyalsoldier** [comment]
请自行处理。
