### ISSUE TITLE
能增加geoip:uk吗？

### ISSUE THREAD

**Issue by jiangjiangflies** [Loyalsoldier/v2ray-rules-dat#312]
希望能增加geoip:uk，把英国IP做一个分类，可以分流看BBC iPlayer/ITV/Channel 5等英国流媒体节目。

**Comment by IIIlllIIllIIIll** [comment]
```geoip:gb```

**Comment by jiangjiangflies** [comment]
> `geoip:gb` [详细列表](https://github.com/Loyalsoldier/geoip/tree/efbec047613e5c9d0daac993ac35bb6814da6e15/text)

非常感谢！我还以为是标签是uk，原来是gb。
