### ISSUE TITLE
geoip可否合并Hackl0us/GeoIP2-CN的数据

### ISSUE THREAD

**Issue by izhangxm** [Loyalsoldier/v2ray-rules-dat#318]
仓库地址

```
https://github.com/Hackl0us/GeoIP2-CN
```

理由：
MaxMind 的 [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/) 免费数据库准确度低：对中国大陆的 IP 地址判定不准，如：香港阿里云的 IP 被判定为新加坡、中国大陆等

**Comment by IIIlllIIllIIIll** [comment]
> 理由： MaxMind 的 [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/) 免费数据库准确度低：对中国大陆的 IP 地址判定不准，如：香港阿里云的 IP 被判定为新加坡、中国大陆等

`CN`（中国大陆）类别下的 IPv4 地址融合了 [ipip.net](https://github.com/17mon/china_ip_list) 和 [@gaoyifan/china-operator-ip](https://github.com/gaoyifan/china-operator-ip)，`CN`（中国大陆）类别下的 IPv6 地址融合了 [MaxMind GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/) 和 [@gaoyifan/china-operator-ip](https://github.com/gaoyifan/china-operator-ip) 
https://github.com/Loyalsoldier/v2ray-rules-dat/blob/d0de54a692c19d036461fc2e48d4f22ff7b492aa/README.md?plain=1#L10

**Comment by Loyalsoldier** [comment]
@izhangxm 

@Hackl0us/GeoIP2-CN 项目 CIDR 数据不是最新的
