### ISSUE TITLE
能不能完善国内的 cidr

### ISSUE THREAD

**Issue by daiyou519** [Loyalsoldier/v2ray-rules-dat#323]
我在openclash中可以找到58.20开头是国内IP，但是在/var/mosdns/geoip_cn.txt找不到。因为tiptime-api.com分流失败了。
https://github.com/vernesong/OpenClash/blob/master/luci-app-openclash/root/etc/openclash/china_ip_route.ipset

**Comment by Loyalsoldier** [comment]
还有比 ipip.net 和 https://github.com/gaoyifan/china-operator-ip 更准的 IP 地址归属？
