### ISSUE TITLE
[建议]能否增加类别dnsmasq-china-list/accelerated-domains.china.conf

### ISSUE THREAD

**Issue by bluaze** [Loyalsoldier/v2ray-rules-dat#324]
现有类别cn一共6万多条，基本上可以认为是[dnsmasq-china-list/accelerated-domains.china.conf](https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf) + apple-cn + google-cn + 少量[@Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom)的cn类别中未被前几项覆盖的条目，其中apple-cn和google-cn是在本项目基于的[@Loyalsoldier/domain-list-custom](https://github.com/Loyalsoldier/domain-list-custom)构建过程中引入

如果apple-cn或google-cn不打算走cn的规则，一般可以单独前置apple-cn或google-cn规则解决，但在有一些场合做不到，比如apple-cn并不显式的指定直连还是代理，而是根据dns解析结果由geoip:cn规则判定（dns解析由chinadns或类似方案提供），这时如果cn的主要部分accelerated-domains.china.conf有自己类别的话就可以使用这个类别来建立规则而不是cn类别

**Comment by Loyalsoldier** [comment]
已增加一个名为 `geosite:china-list` 的类别，只包含 dnsmasq-china-list/accelerated-domains.china.conf 中的域名，见 commit：https://github.com/Loyalsoldier/v2ray-rules-dat/commit/0cfe32fca390ee4ff1c7c054860b0c4ed1e423d3
