### ISSUE TITLE
wl.spotify.com 被误当成了广告

### ISSUE THREAD

**Issue by douglarek** [Loyalsoldier/v2ray-rules-dat#325]
这里：https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/reject-list.txt 。目前这个域名被 spotify 当成了重置密码的跳转链接，不应被屏蔽。

**Comment by Loyalsoldier** [comment]
已修复 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/6c19fb022323ce5e476da776c9eadd4efa80385d
