### ISSUE TITLE
GOOGLE部分域名被加入geosite:cn里面了？

### ISSUE THREAD

**Issue by bluejerry2021** [Loyalsoldier/v2ray-rules-dat#329]
起因：这个礼拜开始ytb打开慢了很多（节点没问题）。
排查：排查了很久，偶然发现V2rayN日记疯狂重复连接同一个域名（显然不正常）
<img width="275" alt="2023-11-09 204557" src="https://github.com/Loyalsoldier/v2ray-rules-dat/assets/94281900/8901eb75-d884-4c83-a245-92be1b5a8f38">
，由于服务端设置了禁止代理CN域名，可是这域名也不是CN域名啊，还是去看看吧。 
          查看服务端Xray日志，果然，发现xray block了Google几个域名：www.gstatic.com，fonts.gstatic.com，ssl.gstatic.com，dl.google.com，fonts.googleapis.com，其他未测试
<img width="266" alt="2023-11-09 204558" src="https://github.com/Loyalsoldier/v2ray-rules-dat/assets/94281900/f5cda150-7db9-4ffd-b0e5-521e9cbedae8">
<img width="248" alt="2023-11-09 204559" src="https://github.com/Loyalsoldier/v2ray-rules-dat/assets/94281900/ec50fded-825d-42f9-891f-196b7b21fca3">
<img width="254" alt="2023-11-09 204560" src="https://github.com/Loyalsoldier/v2ray-rules-dat/assets/94281900/fdbd42ee-4c57-4d15-a693-4d781e77069e">
试过xray croe那边的geosite.dat，是没问题的。
所以是。。。

**Comment by Loyalsoldier** [comment]
将 Proxy 规则放在 Direct 规则上（前）面

**Comment by bluejerry2021** [comment]
> 将 Proxy 规则放在 Direct 规则上（前）
是服务端错误Block了上面几个域名，跟客户端没关系。

**Comment by 17hao** [comment]
@Loyalsoldier 请问下这么做的原因是什么呀？这几个域名直连无法访问，而 geosite:cn 又是比较常见的会配置成直连的一类域名

**Comment by eternalphane** [comment]
Ref: https://github.com/Loyalsoldier/v2ray-rules-dat/issues/478#issuecomment-3708851066
