### ISSUE TITLE
geosite:gfw 列表失效了

### ISSUE THREAD

**Issue by opswill** [Loyalsoldier/v2ray-rules-dat#337]
`Failed to start: main/commands: failed to load config: [/etc/v2fly/config.json] > infra/conf/v4: failed to parse DNS config > infra/conf/synthetic/dns: failed to build nameserver > infra/conf/synthetic/dns: invalid domain rule: geosite:gfw > infra/conf/rule: failed to load geosite: gfw > infra/conf/geodata/standard: list not found in geosite.dat: gfw
V2Ray 5.4.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.2 linux/amd64)
A unified platform for anti-censorship.`

试了其他的geosite:greatfire, geosite:cn等都是可以正常使用的，只有gfw无法读取

**Comment by Loyalsoldier** [comment]
请更新到最新版 V2Ray
