### ISSUE TITLE
更新dat文件后还是这个项目的文件吗

### ISSUE THREAD

**Issue by freedomspiritJohn** [Loyalsoldier/v2ray-rules-dat#341]
我使用的是v2rayn和v2rayng，我替换过两个dat文件后，然后点击了软件的更新geo文件，那么更新之后的两个文件是本项目的文件还是原来软件自带的文件的更新啊

**Comment by Loyalsoldier** [comment]
请到项目 V2RayN 和 V2RayNG 提 issue。

**Comment by freedomspiritJohn** [comment]
> 请到项目 V2RayN 和 V2RayNG 提 issue。

所以更新后就会恢复原来的文件吗？已经不是本项目的更新了吗
