### ISSUE TITLE
各位老师，请问用于openclash中，“非国内的域名集合名称代码”是什么

### ISSUE THREAD

**Issue by wzy105** [Loyalsoldier/v2ray-rules-dat#343]
例如国内域名是 geosite: CN ,那非国内域名集合是 geosite: ？ 。（有不包含“谷歌、苹果大陆可直连”的 非国内域名集合 吗）

**Comment by Loyalsoldier** [comment]
`geosite:geolocation-!cn`

**Comment by wzy105** [comment]
> `geosite:geolocation-!cn`

明白了，感谢L老湿🙏
