### ISSUE TITLE
geosite:cn包含了 www.gstatic.com 导致测速问题

### ISSUE THREAD

**Issue by toyo2333** [Loyalsoldier/v2ray-rules-dat#347]
在代理服务的设置geosite:cn 就block防止回国流量。

结果软件的测速功能就error了（很多软件用http://www.gstatic.com/generate_204测速），以hy2为例
ERROR   TCP error       {"addr": "xxxx:xxxx", "id": "user", "reqAddr": "www.gstatic.com:80", "error": "rejected"}

https://github.com/apernet/hysteria/issues/905

v2fly的geosite.dat 则没有这个问题

这个从到底是合理还是不合理呢?

**Comment by Loyalsoldier** [comment]
问题已知悉，建议自行处理。
