### ISSUE TITLE
如何知道geoip和geosite支持的所有内容

### ISSUE THREAD

**Issue by ttyy33** [Loyalsoldier/v2ray-rules-dat#348]
如下，geoip:cloudflare，可以知道是geoip支持的cloudflare域名的内容，支持其他的内容的内容，如google、
microsoft等域名，这些都不知道

**Comment by IIIlllIIllIIIll** [comment]
https://github.com/Loyalsoldier/geoip/tree/release/text
https://github.com/Loyalsoldier/domain-list-custom/tree/release
https://github.com/v2fly/domain-list-community/tree/master/data
