### ISSUE TITLE
可以增加一个smartdns域名列表吗

### ISSUE THREAD

**Issue by Zephor5** [Loyalsoldier/v2ray-rules-dat#349]
从 `geosite:geolocation-cn` 规则抽取一个域名列表

不太知道怎么解析dat文件

**Comment by Loyalsoldier** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/direct-list.txt

**Comment by Zephor5** [comment]
@Loyalsoldier 我看到这个了，格式不是完全匹配smartdns的规则呀
里面我看还有all:开头的

[smart规则](https://github.com/pymumu/smartdns/issues/1697#issuecomment-1988155533)

**Comment by Zephor5** [comment]
还有麻烦问下这个direct-list和geosite:geolocation-cn完全等价吗

**Comment by Loyalsoldier** [comment]
> 格式不是完全匹配smartdns的规则呀 里面我看还有all:开头的

请自行处理

> 还有麻烦问下这个direct-list和geosite:geolocation-cn完全等价吗

等价
