### ISSUE TITLE
itdog.plus不应该属于cn

### ISSUE THREAD

**Issue by charliez0** [Loyalsoldier/v2ray-rules-dat#350]
itdog.plus不应该属于cn

**Comment by Loyalsoldier** [comment]
请到上游项目反馈：https://github.com/felixonmars/dnsmasq-china-list

**Comment by charliez0** [comment]
https://github.com/felixonmars/dnsmasq-china-list/issues/483#issuecomment-1848590682

**Comment by charliez0** [comment]
看上去这个上游是用错地方了

**Comment by charliez0** [comment]
👀

**Comment by Loyalsoldier** [comment]
没有更好、更完整的针对中国域名的项目了
