### ISSUE TITLE
大佬，能在规则里加入一些GPT和copilot的吗

### ISSUE THREAD

**Issue by javazwz123** [Loyalsoldier/v2ray-rules-dat#351]
如题，用了规则之后，chatgpt和windows自带的copilot都不咋好用，手动一个个的添加了白名单，但是还是没有完全正常，一卡一卡的，用了全局就是完美，不知道这个规则怎么能弄的干净

**Comment by Loyalsoldier** [comment]
使用 `geosite:openai` 和 `geosite:microsoft`
