### ISSUE TITLE
海外版微信表情包搜索需要走代理

### ISSUE THREAD

**Issue by aplixy** [Loyalsoldier/v2ray-rules-dat#353]
目前海外版WeChat没走代理，导致表情包搜索结果展示变慢，甚至有时搜不出来，类似的还有WeChat登录时旧手机扫新手机二维码也加载不出来，不知道对于WeChat聊天信息收发有多大影响

**Comment by Loyalsoldier** [comment]
将 `wechat.com` 设置为代理应该可以解决
