### ISSUE TITLE
services.googleapis.cn似乎并未被成功合入proxy-list

### ISSUE THREAD

**Issue by NXY666** [Loyalsoldier/v2ray-rules-dat#357]
虽然它确实出现在了hidden分支中，但是发布新版本时并没有被成功加入proxy列表。

是出了什么问题吗？

**Comment by Loyalsoldier** [comment]
已修复：https://github.com/Loyalsoldier/v2ray-rules-dat/commit/c62962b3a363e3c4d6905ee3336547d7d07967a1
