### ISSUE TITLE
我想让大部分微软服务直连，少部分（Copilot、Bing、网页版OneDirve）代理，应该怎么做？

### ISSUE THREAD

**Issue by PandaFiredoge** [Loyalsoldier/v2ray-rules-dat#359]
我想让**大部分**微软服务直连，少部分（Copilot、Bing、**网页版**OneDirve）代理，应该怎么做？

**Comment by Loyalsoldier** [comment]
找出 Copilot、Bing、网页版 OneDirve 使用的域名，设置为代理。再把 `geosite:microsoft` 设置为直连
