### ISSUE TITLE
为什么 whois.gtld.knet.cn 在阻断里面？

### ISSUE THREAD

**Issue by cangyin** [Loyalsoldier/v2ray-rules-dat#36]
如题

Qv2ray 截图
![image](https://user-images.githubusercontent.com/50256182/87038898-f4cc6780-c220-11ea-86a8-00c680cc1c18.png)

**Comment by Loyalsoldier** [comment]
已于 https://github.com/Loyalsoldier/v2ray-rules-dat/commit/624531bc78d9387ff720dc9123ba2429de7d2621 移除，会在明天生成的 `geosite.dat` 中生效
