### ISSUE TITLE
gstatic等国外地址好像在cn里，好像不太合理

### ISSUE THREAD

**Issue by bokemanoh** [Loyalsoldier/v2ray-rules-dat#361]
白名单下（默认全部代理，只有cn ip,domain直连），咕咕等这些被重点关注、服务功能受地理位置限制的公司，在连接其各种域名时，使用直连、使用其国内服务器，这不好吧？
一方面连接稳定性不会好吧？
另外地理位置判断上有隐患。解决地理位置判断问题，也是这些软件、服务的存在意义之一，不是吗？

再有，不是有专门的规则集只代理被阻断干扰的地址（无论国内外默认全部直连，然后只有被阻断的地址代理），有需要的去用那个规则集不就好了吗，为什么要在白名单里把gstatic这类国外地址加到cn里？

-----
前些日子，更新最新数据库后，在使用中观察到，还有很多其他国外域名也在cn里，不是只有gstatic，这是为什么呢？

使用白名单（国内地址直连），结果gstatic和很多其他国外域名也是直连的，那些域名都是有阻断/干扰的，导致相应某些站点页面内容加载缓慢/失败。

换成全局就恢复正常。

以前几次更新，在使用中没注意到页面加载缓慢/失败，所以没注意到是不是也有相应问题。

该问题似乎涉及域名较多，很多域名的命名也没有太多规律，手动挨个撸有点累。

**Comment by Loyalsoldier** [comment]
将 `geosite:google-cn` 设置为代理，放在 `geosite:cn` 的前面
