### ISSUE TITLE
请问full 是什么意思?

### ISSUE THREAD

**Issue by luobeichen** [Loyalsoldier/v2ray-rules-dat#362]
在您的release 中部分网址中存在full:前缀,而部分没有

**Comment by luobeichen** [comment]
另外我发现前缀为regexp:的网址使用的并不是标准的通配符,请问我应该如何去解析,或者说我应该如何去理解它?

**Comment by Loyalsoldier** [comment]
`full` 表示只匹配该域名，不包括子域名。`regexp` 是正则表达式匹配规则
