### ISSUE TITLE
請問geosite:tld-cn的定義？

### ISSUE THREAD

**Issue by ZmdnaHF0ZmFqYXZ0O** [Loyalsoldier/v2ray-rules-dat#37]
因爲在示例的配置中有見到geosite:tld-cn，請問geosite:tld-cn的域名範圍和定義是什麼？和geosite:cn有什麼區別？謝謝！

**Comment by ZmdnaHF0ZmFqYXZ0O** [comment]
已經在https://www.v2ray.com/chapter_02/03_routing.html#dlc找到：
tld-cn: 包含了所有 .cn 和 .中国 结尾的域名

**Comment by Loyalsoldier** [comment]
每个 `geosite:filename` 对应 `domain-list-community` 的 `data` 文件夹中的同名文件 https://github.com/v2fly/domain-list-community/tree/master/data

**Comment by ZmdnaHF0ZmFqYXZ0O** [comment]
> 每个 `geosite:filename` 对应 `domain-list-community` 项目里 `data` 文件夹中的同名文件 https://github.com/v2fly/domain-list-community/tree/master/data

感謝回覆！
再請教示例配置中路由的一段配置：
{
        "type": "field",
        "outboundTag": "Proxy",
        "network": "tcp,udp"
      }
這段配置因爲沒有任何範圍的定義，所以在配置中有產生什麼作用嗎？去掉這段也不會對配置有任何影響？

**Comment by Loyalsoldier** [comment]
`network` 就是范围定义，日常浏览互联网就是 TCP 和 UDP 两种协议的流量。这段配置的意思是，所有没有命中前面规则的流量，都会命中这条规则。去掉的话，对日常访问互联网不会有什么影响。

**Comment by ZmdnaHF0ZmFqYXZ0O** [comment]
> `network` 就是范围定义，日常浏览互联网就是 TCP 和 UDP 两种协议的流量。这段配置的意思是，所有没有命中前面规则的流量，都会命中这条规则。去掉的话，对日常访问互联网不会有什么影响。

再次感謝你清晰的回覆！
