### ISSUE TITLE
geosite:cn中缺失geosite:geolocation-cn的部分内容

### ISSUE THREAD

**Issue by DebussyS** [Loyalsoldier/v2ray-rules-dat#372]
原版geosite:cn [https://github.com/v2fly/domain-list-community/blob/master/data/cn](url) 包含geolocation-cn内容，而本项目中缺失例如**douyucdn.com**等地址

**Comment by Loyalsoldier** [comment]
https://github.com/v2fly/domain-list-community/blob/master/data/douyu 没有 douyucdn.com 这个域名啊
