### ISSUE TITLE
category-games@!cn内规则只有一条

### ISSUE THREAD

**Issue by Kryo123456** [Loyalsoldier/v2ray-rules-dat#375]
但是category-games@cn规则里面似乎没有问题，请问这种情况是正常的么？

**Comment by Kryo123456** [comment]
> 没看懂你想表达什么

![屏幕截图 2024-08-23 202621](https://github.com/user-attachments/assets/8c20d19c-3f3f-4498-8a15-d4317b3bbcba)
我的意思是category-games@!cn的规则数目不对。

**Comment by Loyalsoldier** [comment]
`@!cn` 不是 `@cn` 的取反。大部分域名是不带 `@attr` 属性的

**Comment by Kryo123456** [comment]
> `@!cn` 不是 `@cn` 的取反。大部分域名是不带 `@attr` 属性的

那只有1条规则也不是正常的情况吧。
