### ISSUE TITLE
有没有规则可以直连非匹配的域名的

### ISSUE THREAD

**Issue by Wangxuechi** [Loyalsoldier/v2ray-rules-dat#388]
我用的是v2rayn，在配置规则时只能明确直连的域名，但是有没有能判断域名如果不是列表里面的就直连，如果在就代理

**Comment by Loyalsoldier** [comment]
将规则设置为走代理

**Comment by Wangxuechi** [comment]
> 将规则设置为走代理

我有点没听懂贴两张设置的图上来，就是我只想让chatgpt.com这个域名走代理，其他的都是直连。但是按照这上面的方法设置后，还是所有流量走代理
![image](https://github.com/user-attachments/assets/ea53b92a-d0a0-43f6-85e0-87b80afe9f0b)

**Comment by Loyalsoldier** [comment]
`chatgpt` 那条规则删掉 port 匹配，第二条规则设置为 direct，或者直接使用 `geosite:openai`。

**Comment by Wangxuechi** [comment]
![image](https://github.com/user-attachments/assets/c348d948-ed7b-4e83-bc11-adb37b16fcef)
![image](https://github.com/user-attachments/assets/cb45c648-42ab-4468-95a9-3d771b67735d)
![image](https://github.com/user-attachments/assets/3e72fb4b-ebbb-4462-ab69-23b4404bc58f)
照你说的做了，但是还是所有流量都走的代理

**Comment by Wangxuechi** [comment]
![image](https://github.com/user-attachments/assets/699d8503-6a9e-442d-a882-253af554c177)
我用的内核是v2fly也试过xray，但都一样
