### ISSUE TITLE
合并如MVPS host等清单中列出的域名。

### ISSUE THREAD

**Issue by RealXuChe** [Loyalsoldier/v2ray-rules-dat#39]
参见: https://github.com/v2fly/domain-list-community/issues/111

如觉得有风险的话，可以不合并到category-ads而是另立category

**Comment by Loyalsoldier** [comment]
MVPS host 的 LICENSE 跟本项目 LICENSE 不兼容。另外 Dan Pollock's hosts 很出名吗？看不到这个项目的使用数据，不好对项目质量做评判。

**Comment by RealXuChe** [comment]
互联网时光机上这个项目的[最早存档](https://web.archive.org/web/20011216052951/https://someonewhocares.org/hosts/)是在2001年12月16日，能持续维护20年，应该可以证明不是什么垃圾项目了，我也只是从前天开始用的，到目前为止没发现问题。
至于使用量，确实在网上对此的讨论比较少，估计使用者不会太多。

**Comment by Loyalsoldier** [comment]
欢迎使用一两个月后来反馈该项目可靠性 😊

**Comment by Loyalsoldier** [comment]
已在 e045a62c16730df7ae850581e3fd70cad7951a03 中加入 Dan Pollock hosts，会持续观察一段时间，看看有没有错误。如果错误太多，会移除。
