### ISSUE TITLE
安卓版如何使用？

### ISSUE THREAD

**Issue by XinXinkkk** [Loyalsoldier/v2ray-rules-dat#4]
如题

**Comment by Loyalsoldier** [comment]
需要自行确认使用的客户端的规则文件是不是跟 V2Ray 使用的一样。如果使用的是 V2Ray 的规则文件，则可以使用本项目的规则文件直接替换掉原来的。

**Comment by reed0214** [comment]
安卓端我搜了下目录,好纳闷的事情是没有找v2ray相关鲁姆以及geoip.data和geosite.data文件.

**Comment by wangfeng35** [comment]
> 安卓端我搜了下目录,好纳闷的事情是没有找v2ray相关目录以及geoip.data和geosite.data文件.

安卓端规则看这个：https://github.com/PaPerseller/chn-iplist

**Comment by reed0214** [comment]
> 
> 
> > 安卓端我搜了下目录,好纳闷的事情是没有找v2ray相关目录以及geoip.data和geosite.data文件.
> 
> 安卓端规则看这个：https://github.com/PaPerseller/chn-iplist

好的,谢谢了

**Comment by txyyh** [comment]
这两文件在base.apk里面
另外问一句可以直接拷贝对应list填充吗？
