### ISSUE TITLE
请问可否增加一份 AutoProxy 格式的 proxy-list.txt。

### ISSUE THREAD

**Issue by dna1982** [Loyalsoldier/v2ray-rules-dat#41]
是为了在 SwitchyOmega 里用。
官方的 gfwlist 实在是一言难尽。

**Comment by Loyalsoldier** [comment]
本项目还是想纯粹点，只服务 V2Ray 用户。[Release 分支](https://github.com/Loyalsoldier/v2ray-rules-dat/tree/release) 里包含了本项目生成的各种列表，建议自己生成 AutoProxy 格式的。
