### ISSUE TITLE
作者可以出一个v2rayN的配置方法吗？

### ISSUE THREAD

**Issue by somelee** [Loyalsoldier/v2ray-rules-dat#44]
作者可以出一个v2rayN的配置方法吗？

v2rayN的分流方法太过粗糙，可以请作者出一个v2rayN的模板吗？

Regard，

**Comment by Loyalsoldier** [comment]
没有 Windows 系统，不好测试。另外可以看看这个 [issue](https://github.com/Loyalsoldier/v2ray-rules-dat/issues/5)

**Comment by somelee** [comment]
> 没有 Windows 系统，不好测试。另外可以看看这个 [issue](https://github.com/Loyalsoldier/v2ray-rules-dat/issues/5)

好滴
