### ISSUE TITLE
请问有没有更准确的IP地址归属地分类

### ISSUE THREAD

**Issue by badO1a5A90** [Loyalsoldier/v2ray-rules-dat#45]
CN的IP已经得到了很大的增强，但Maxmind的IP地址的所属地似乎并不准确，比如google在香港的服务器地址 172.217.24.68 ，他会任务属于US。
所以请问一下，有没有更准确的识别IP归属地的方式

**Comment by Loyalsoldier** [comment]
大陆服务的话，ipip.net 应该是比较准的，其次 ip.sb 采用了多方的商业服务，应该也比较准。国外的服务，MaxMind 有免费版，也有商业付费版。目前而言，免费的只有 MaxMind 提供的全球 IP 数据覆盖面是最全的，但是准确性欠缺。

如果这些都看不上，只有商业付费版能满足你。

**Comment by badO1a5A90** [comment]
thx！
