### ISSUE TITLE
[建议]新建一个GFWList的类别

### ISSUE THREAD

**Issue by YGH-Coder** [Loyalsoldier/v2ray-rules-dat#49]
个人认为 `黑名单` 比 `!cn` 效率更高, 因为并不是所有的国外域名都需要被代理.

**Comment by Loyalsoldier** [comment]
Done in https://github.com/Loyalsoldier/v2ray-rules-dat/commit/3b5d3a6e3ce04ea940a4c979b8bf2f459bcd87f6
