### ISSUE TITLE
v2rayN修改配置文件自动变回原样？

### ISSUE THREAD

**Issue by KNedwin** [Loyalsoldier/v2ray-rules-dat#5]
你好，请问为什么我按照你所说的方法修改config.json文件后，每次重新打开V2rayN（win）客户端，我的配置文件又变回了原样。这样能正常使用吗？

**Comment by joiln** [comment]
> 你好，请问为什么我按照你所说的方法修改config.json文件后，每次重新打开V2rayN（win）客户端，我的配置文件又变回了原样。这样能正常使用吗？

请问一下，修改V2ray配置文件，指的是修改服务器上的config.json吗？

**Comment by KNedwin** [comment]
> > 你好，请问为什么我按照你所说的方法修改config.json文件后，每次重新打开V2rayN（win）客户端，我的配置文件又变回了原样。这样能正常使用吗？
> 
> 请问一下，修改V2ray配置文件，指的是修改服务器上的config.json吗？

我改的是客户端这里的config.json

**Comment by joiln** [comment]
> > > 你好，请问为什么我按照你所说的方法修改config.json文件后，每次重新打开V2rayN（win）客户端，我的配置文件又变回了原样。这样能正常使用吗？
> > 
> > 
> > 请问一下，修改V2ray配置文件，指的是修改服务器上的config.json吗？
> 
> 我改的是客户端这里的config.json

我觉应该改服务端的吧

**Comment by KNedwin** [comment]
> > > > 你好，请问为什么我按照你所说的方法修改config.json文件后，每次重新打开V2rayN（win）客户端，我的配置文件又变回了原样。这样能正常使用吗？
> > > 
> > > 
> > > 请问一下，修改V2ray配置文件，指的是修改服务器上的config.json吗？
> > 
> > 
> > 我改的是客户端这里的config.json
> 
> 我觉应该改服务端的吧

我去试试修改下。

**Comment by Loyalsoldier** [comment]
我提供的配置是客户端的配置。
我没有在使用 Windows 系统，没法帮忙测试。我猜应该需要通过 V2RayN 界面来修改配置？或者对 V2RayN 的原版配置动手脚？

**Comment by KNedwin** [comment]
> 我提供的配置是客户端的配置。
> 我没有在使用Windows系统，没法帮忙测试。我猜应该需要通过V2RayN界面来修改配置？或者对V2RayN的替代配置动手脚？

我在v2rayn上找到了办法配置Routing ，但是dns的还是看不懂如何改。
v2rayn的配置文件里dns只有一行代码。
 "remoteDNS": "1.1.1.1:53,114.114.114.114:53,8.8.8.8,223.5.5.5",

**Comment by huang826** [comment]
我也碰到相同问题了，win的config是这样的
  "dns": {
    "servers": [
      "119.29.29.29",
      "1.1.1.1"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "ip": null,
        "domain": null
      }
    ]
  }

**Comment by Loyalsoldier** [comment]
@huang826 
参考配置的写法让你误会了，我改了一下，看现在最新的（其实就是 JSON）。
原本在最外层加一对大括号是为了表明那是一段 JSON 配置，结果你们都看不懂，改成现在这样应该看懂了吧：

```json
"dns": {
  "servers": [
    {
      "address": "1.1.1.1",
      "port": 53,
      "domains": [
        "geosite:geolocation-!cn"
      ]
    },
    {
      "address": "114.114.114.114",
      "port": 53,
      "domains": [
        "geosite:cn"
      ]
    },
    "8.8.8.8",
    "223.5.5.5"
  ]
}
```

**Comment by Loyalsoldier** [comment]
项目说明里新增了自用 V2Ray 客户端完整配置，可以参考一下。

**Comment by wxl1999** [comment]
别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义配置

**Comment by wangfeng35** [comment]
> 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置

那就是没法设置么？

**Comment by wxl1999** [comment]
> > 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置
> 
> 那就是没法设置么？

除非自己改v2rayN代码，不过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就行

**Comment by wangfeng35** [comment]
> 过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就



> > > 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置
> > 
> > 
> > 那就是没法设置么？
> 
> 除非自己改v2rayN代码，不过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就行

请问是下载完两个.dat文件后在GUI参数设置的路由设置里进行如下设置么：
1代理的Domain或IP设置为geosite:geolocation-!cn；
2直连的Domain或IP设置为geosite:geolocation-cn；
3阻止的Domain或IP设置为geosite:category-ads-all；

这样对么，谢谢！

**Comment by wxl1999** [comment]
> > 过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就
> 
> > > > 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置
> > > 
> > > 
> > > 那就是没法设置么？
> > 
> > 
> > 除非自己改v2rayN代码，不过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就行
> 
> 请问是下载完两个.dat文件后在GUI参数设置的路由设置里进行如下设置么：
> 1代理的Domain或IP设置为geosite:geolocation-!cn；
> 2直连的Domain或IP设置为geosite:geolocation-cn；
> 3阻止的Domain或IP设置为geosite:category-ads-all；
> 
> 这样对么，谢谢！

![image](https://user-images.githubusercontent.com/47387759/74334526-06762400-4dd5-11ea-9c53-aa15645381de.png)
![image](https://user-images.githubusercontent.com/47387759/74334582-273e7980-4dd5-11ea-98c9-4002e2aa2116.png)
![image](https://user-images.githubusercontent.com/47387759/74334844-b21f7400-4dd5-11ea-9570-b863819c2cee.png)
第一张图的edx可以忽略，是我自己加的

**Comment by wangfeng35** [comment]
> 第一张图的edx可以忽略，是我自己加的

非常感谢 学习了

**Comment by Itzamana** [comment]
> > > 过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就
> > 
> > 
> > > > > 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置
> > > > 
> > > > 
> > > > 那就是没法设置么？
> > > 
> > > 
> > > 除非自己改v2rayN代码，不过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就行
> > 
> > 
> > 请问是下载完两个.dat文件后在GUI参数设置的路由设置里进行如下设置么：
> > 1代理的Domain或IP设置为geosite:geolocation-!cn；
> > 2直连的Domain或IP设置为geosite:geolocation-cn；
> > 3阻止的Domain或IP设置为geosite:category-ads-all；
> > 这样对么，谢谢！
> 
> ![image](https://user-images.githubusercontent.com/47387759/74334526-06762400-4dd5-11ea-9c53-aa15645381de.png)
> ![image](https://user-images.githubusercontent.com/47387759/74334923-e98e2080-4dd5-11ea-8a5e-dab29f205b54.png)
> ![image](https://user-images.githubusercontent.com/47387759/74334844-b21f7400-4dd5-11ea-9570-b863819c2cee.png)
> 第一张图的edx可以忽略，是我自己加的

感谢分享v2rayN的使用方法，我一直以为覆盖到目录替换原文件就可以了…原来还得手动添加一下规则…

**Comment by damfu** [comment]
v2rayN可以使用纯配置文件的，只不过界面上的大部分功能都不能用了，添加服务器那里有相关的入口。

**Comment by lon91ong** [comment]
> > > 过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就
> > 
> > 
> > > > > 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置
> > > > 
> > > > 
> > > > 那就是没法设置么？
> > > 
> > > 
> > > 除非自己改v2rayN代码，不过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就行
> > 
> > 
> > 请问是下载完两个.dat文件后在GUI参数设置的路由设置里进行如下设置么：
> > 1代理的Domain或IP设置为geosite:geolocation-!cn；
> > 2直连的Domain或IP设置为geosite:geolocation-cn；
> > 3阻止的Domain或IP设置为geosite:category-ads-all；
> > 这样对么，谢谢！
> 
> ![image](https://user-images.githubusercontent.com/47387759/74334526-06762400-4dd5-11ea-9c53-aa15645381de.png)
> ![image](https://user-images.githubusercontent.com/47387759/74334923-e98e2080-4dd5-11ea-8a5e-dab29f205b54.png)
> ![image](https://user-images.githubusercontent.com/47387759/74334844-b21f7400-4dd5-11ea-9570-b863819c2cee.png)
> 第一张图的edx可以忽略，是我自己加的

基础设置那里也来一张截图吧！ 不知道自己设置的对不对

**Comment by zakizou** [comment]
> 
> 
> > > 过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就
> > 
> > 
> > > > > 别纠结了，这个应该是v2rayN这个客户端自己的问题，没有开放自定义config.json，只会按照GUI里面的参数设置进行相应配置
> > > > 
> > > > 
> > > > 那就是没法设置么？
> > > 
> > > 
> > > 除非自己改v2rayN代码，不过除了dns没法儿设置成一样的，其他的直接在GUI里面的参数设置填上就行
> > 
> > 
> > 请问是下载完两个.dat文件后在GUI参数设置的路由设置里进行如下设置么：
> > 1代理的Domain或IP设置为geosite:geolocation-!cn；
> > 2直连的Domain或IP设置为geosite:geolocation-cn；
> > 3阻止的Domain或IP设置为geosite:category-ads-all；
> > 这样对么，谢谢！
> 
> ![image](https://user-images.githubusercontent.com/47387759/74334526-06762400-4dd5-11ea-9c53-aa15645381de.png)
> ![image](https://user-images.githubusercontent.com/47387759/74334923-e98e2080-4dd5-11ea-8a5e-dab29f205b54.png)
> ![image](https://user-images.githubusercontent.com/47387759/74334844-b21f7400-4dd5-11ea-9570-b863819c2cee.png)
> 第一张图的edx可以忽略，是我自己加的

感谢，终于知道怎么配置了。国内的主要网站不走代理，快了很多。

**Comment by Radium-bit** [comment]
其实很简单，修改V2rayN客户端的的配置不是修改 config.json 而应该修改 **guiNConfig.json**
每次V2aRayN启动时，会自动将guiNConfig.json覆盖到 config.json 中。
所以，对于V2RayN来讲，真正的客户端配置文件是 **guiNConfig.json**

**Comment by xtianxx** [comment]
> 其实很简单，修改V2rayN客户端的的配置不是修改 config.json 而应该修改 **guiNConfig.json** 每次V2aRayN启动时，会自动将guiNConfig.json覆盖到 config.json 中。 所以，对于V2RayN来讲，真正的客户端配置文件是 **guiNConfig.json**

我下载的这个没有guiNConfig.json
