### ISSUE TITLE
itunes/ mac app store 服务总是走代理

### ISSUE THREAD

**Issue by Owisky** [Loyalsoldier/v2ray-rules-dat#50]
听音乐/下载软件，流量撑不住呀；而这些url 都是国内正常解析的；

可否在 上游 或者  本项目中解决？

<img width="693" alt="Screen Shot 2020-10-29 at 11 54 06 PM" src="https://user-images.githubusercontent.com/9482256/97599060-9252dd80-1a42-11eb-8564-6d79d9804015.png">

**Comment by Loyalsoldier** [comment]
看这里：https://github.com/Loyalsoldier/v2ray-rules-dat#geositedat-1
