### ISSUE TITLE
How to use these rules with switchyOmega extension?

### ISSUE THREAD

**Issue by yasershadan** [Loyalsoldier/v2ray-rules-dat#51]
is there any step by step guide to setup v2ray proxy with switchyOmega with my customized rules in v2rayN?
thanks

**Comment by Loyalsoldier** [comment]
I suggest you read the doc and guide here: https://www.v2fly.org/en_US/ and https://guide.v2fly.org/en_US/

**Comment by Loyalsoldier** [comment]
BTW, this is the install script for V2Ray on Debian / CentOS / Fedora / openSUSE: https://github.com/v2fly/fhs-install-v2ray

**Comment by yasershadan** [comment]
> I suggest you read the doc and guide here: https://www.v2fly.org/en_US/ and https://guide.v2fly.org/en_US/

sorry I didn't find relevant content to my question.

**Comment by Loyalsoldier** [comment]
1. install v2ray on your server and local computer.
2. v2ray client (on your local computer) should listen to a local port (eg. 1080) on socks5 protocol.
3. configure your SwitchyOmega to use the local socks5 proxy `127.0.0.1:1080` served by v2ray client.

So, the hardest part is to install v2ray and configure v2ray properly. Am I clear?

**Comment by yasershadan** [comment]
these instructions are ok but switchyomega won't listen to v2ray rules.
I want it to use v2ray rules for directing some connections and blocking others

**Comment by Loyalsoldier** [comment]
Then, don't use Switchyomega. Chrome and Safari will automatically use local socks5 proxy set in computer network. And if you are using Firefox, you can either set local socks5 proxy for it manually, or let it use the proxy set in computer network.

**Comment by yasershadan** [comment]
> Then, don't use Switchyomega. Chrome and Safari will automatically use socks5 proxy set in system network. And if you are using Firefox, you can either set local socks5 proxy for it manually, or set to let it "use system proxy settings" in Firefox network setting section.
> 
> ![image](https://user-images.githubusercontent.com/10487845/97772388-7c980200-1b81-11eb-8e2a-4a80f4a5cb26.png)
> 
> The point is to use v2ray to listen to a local port on your computer on socks5 protocol.

this is ok but I think there is a solution as in this link with switchyOmega in this [link](https://3385706034.gitbook.io/note/v2ray-swithyomega)
I don't Understand Chinese language. I would thank you if you know if this tutorial helps.
thanks

**Comment by Loyalsoldier** [comment]
If you have already set Proxifier successfully, you really don't need SwitchyOmega. All browser traffics will go through Proxifier including browsers as long as you don't set it to `Direct` in Proxifier.

**Comment by yasershadan** [comment]
> If you have already set Proxifier successfully, you really don't need SwitchyOmega. All traffics will go through Proxifier then be redirected to v2rayN including browsers' as long as you don't set your browser to `Direct` rule in Proxifier.
yes thats a way
thanks

**Comment by yasershadan** [comment]
> If you have already set Proxifier successfully, you really don't need SwitchyOmega. All traffics will go through Proxifier then be redirected to v2rayN including browsers' as long as you don't set your browser to `Direct` rule in Proxifier.

yes thats a way
 thanks
