### ISSUE TITLE
add some filters

### ISSUE THREAD

**Issue by yasershadan** [Loyalsoldier/v2ray-rules-dat#52]
can you please add these filters to be used in geoip and geosite?
1. [addblocker for persian sites](https://cdn.rawgit.com/SlashArash/adblockfa/master/adblockfa.txt)
2. [Adblock Warning Removal List Specialization: removes anti-adblock warnings and other obtrusive messages
](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt)
3. [EasyList Cookie List, Specialization: cookies banners, GDPR overlay windows and other privacy-related notices](https://easylist-downloads.adblockplus.org/easylist-cookie.txt)
all of these filters are from [Known Adblock Plus subscriptions](https://adblockplus.org/subscriptions)

**Comment by Loyalsoldier** [comment]
I suggest you use these lists in AdBlock Plus or uBlock Origin. Because V2Ray can only block a whole domain or host, it can not block popups and HTML elements.

Most lists you listed above will need the ability to block HTML elements to take effect, that's not what V2Ray can do.

**Comment by yasershadan** [comment]
> I suggest you use these lists in AdBlock Plus or uBlock Origin. Because V2Ray can only block a whole domain or host, it can not block popups and HTML elements.
> 
> Most lists you listed above will need the ability to block HTML elements to take effect, that's not what V2Ray can do.

can you tell me how I can add Persian site ads list to my geosite in order to categorize them as ads?

**Comment by Loyalsoldier** [comment]
Oh that's a long story. The shorter one is to add a file(eg. `myads`) in `data` directory of this repo, and run the code to build it. Then you can use it as follows:

```
"rules": [
    {
      "type": "field",
      "outboundTag": "Reject",
      "domain": [
        "geosite:category-ads-all",
        "geosite:myads"
      ]
    },
```

**Comment by yasershadan** [comment]
> Oh that's a long story. The shorter one is to add a file(eg. `myads`) in `data` directory of this repo(https://github.com/v2fly/domain-list-community ), which contains all the ads hosts/domains that you need, and run the code to build your own `geosite.dat`. Then you can use it as follows:
> 
> ```
> "rules": [
>     {
>       "type": "field",
>       "outboundTag": "Reject",
>       "domain": [
>         "geosite:category-ads-all",
>         "geosite:myads"
>       ]
>     },
> ```


I think I would use ABP. its an easier option ;)
