### ISSUE TITLE
direct connection for whatsapp hosts and ip's

### ISSUE THREAD

**Issue by yasershadan** [Loyalsoldier/v2ray-rules-dat#56]
Hi
I want to make direct connection for whatsapp how can I do that?
is there any simple rule to exclude whatsapp hosts from proxy in v2rayN?
thanks

**Comment by Loyalsoldier** [comment]
Every file in `data` directory( https://github.com/v2fly/domain-list-community/tree/master/data ) can be used in `routing` section like following:

```
{
      "type": "field",
      "outboundTag": "direct",
      "domain": [
        "geosite:filename1",
        "geosite:filename2"
      ]
    }
```

So, you can set `whatsapp` to direct like:

```
{
      "type": "field",
      "outboundTag": "direct",
      "domain": [
        "geosite:whatsapp"
      ]
    }
``` 

Every file can be used in `dns` section like following if you want specific hosts to use specific DNS (support DoH and DoT):

```
"dns": {
  "servers": [
    {
      "address": "1.1.1.1",
      "port": 53,
      "domains": [
        "geosite:filename1",
        "geosite:filename2"
      ]
    },
    "8.8.8.8"
  ]
}
```

**Comment by Loyalsoldier** [comment]
And you should put the rules of `whatsapp` before `geolocation-!cn` because the latter one includes `whatsapp` hosts.

```
{
      "type": "field",
      "outboundTag": "direct",
      "domain": [
        "geosite:whatsapp"
      ]
    },
{
      "type": "field",
      "outboundTag": "proxy",
      "domain": [
        "geosite:geolocation-!cn"
      ]
    }
```

**Comment by yasershadan** [comment]
instead of all of these
can I do as picture in gui?
![image](https://user-images.githubusercontent.com/61946187/98529491-ebb4db00-2292-11eb-899b-52a3cc2386be.png)

**Comment by yasershadan** [comment]
> Every file in `data` directory( https://github.com/v2fly/domain-list-community/tree/master/data ) can be used in `routing` section like following:
> 
> ```
> {
>       "type": "field",
>       "outboundTag": "direct",
>       "domain": [
>         "geosite:filename1",
>         "geosite:filename2"
>       ]
>     }
> ```
> 
> So, you can set `whatsapp` to direct like:
> 
> ```
> {
>       "type": "field",
>       "outboundTag": "direct",
>       "domain": [
>         "geosite:whatsapp"
>       ]
>     }
> ```
> 
> Every file can be used in `dns` section like following if you want specific hosts to use specific DNS (also support DoH):
> 
> ```
> "dns": {
>   "servers": [
>     {
>       "address": "1.1.1.1",
>       "port": 53,
>       "domains": [
>         "geosite:filename1",
>         "geosite:filename2"
>       ]
>     },
>     "8.8.8.8"
>   ]
> }
> ```

my rules are different than yours.
I live in a country other than china and I want to get direct connection on another geoip
I typed geosite:whatsapp in direct connction of the gui routing setting but it didn't work

**Comment by Loyalsoldier** [comment]
As far as i know, each v2ray GUI client for Windows does NOT support v2ray's layer routing as I described above, so I suggest you use v2ray-core directly and write your own JSON configuration.

**Comment by Loyalsoldier** [comment]
BTW, which proxy protocol are you using, VMess, Shadowsocks or socks5?

**Comment by yasershadan** [comment]
is there a full guide for how I write one?

**Comment by Loyalsoldier** [comment]
Translate this into your language https://www.v2fly.org/config/overview.html

**Comment by yasershadan** [comment]
> Translate this into your language https://www.v2fly.org/config/overview.html

thanks

**Comment by fsheidaiee** [comment]
> Every file in `data` directory( https://github.com/v2fly/domain-list-community/tree/master/data ) can be used in `routing` section like following:
> 
> ```
> {
>       "type": "field",
>       "outboundTag": "direct",
>       "domain": [
>         "geosite:filename1",
>         "geosite:filename2"
>       ]
>     }
> ```
> 
> So, you can set `whatsapp` to direct like:
> 
> ```
> {
>       "type": "field",
>       "outboundTag": "direct",
>       "domain": [
>         "geosite:whatsapp"
>       ]
>     }
> ```
> 
> Every file can be used in `dns` section like following if you want specific hosts to use specific DNS (also support DoH):
> 
> ```
> "dns": {
>   "servers": [
>     {
>       "address": "1.1.1.1",
>       "port": 53,
>       "domains": [
>         "geosite:filename1",
>         "geosite:filename2"
>       ]
>     },
>     "8.8.8.8"
>   ]
> }
> ```

i have configured the json file as you said but I realized that whatsapp uses ranges of ip's and this rule; "geosite:whatsapp"
only effects on a very small range ip's. and the majority of the data (almost all of it) still going through proxy.
I have search and found all facebook ip's and when I use those ip's it works. but those ip's won't help because I don't want my facebook app goes through direct connection.
can you find the latest whatsapp (only whatsapp not facebook) ip ranges?
thanks

**Comment by Loyalsoldier** [comment]
> i have configured the json file as you said but I realized that whatsapp uses ranges of ip's and this rule; "geosite:whatsapp"
> only effects on a very small range ip's. and the majority of the data (almost all of it) still going through proxy.
> I have search and found all facebook ip's and when I use those ip's it works. but those ip's won't help because I don't want my facebook app goes through direct connection.
> can you find the latest whatsapp (only whatsapp not facebook) ip ranges?
> thanks

Just use Proxifer to direct the traffic of whatsapp.

**Comment by fsheidaiee** [comment]
> > i have configured the json file as you said but I realized that whatsapp uses ranges of ip's and this rule; "geosite:whatsapp"
> > only effects on a very small range ip's. and the majority of the data (almost all of it) still going through proxy.
> > I have search and found all facebook ip's and when I use those ip's it works. but those ip's won't help because I don't want my facebook app goes through direct connection.
> > can you find the latest whatsapp (only whatsapp not facebook) ip ranges?
> > thanks
> 
> Just use Proxifer to direct the traffic of whatsapp.

the problem is in android

**Comment by Loyalsoldier** [comment]
> the problem is in android

There is no silver bullet on this.
