### ISSUE TITLE
how to use custum rules in shadowsocks application

### ISSUE THREAD

**Issue by fsheidaiee** [Loyalsoldier/v2ray-rules-dat#59]
Hi 
is there anyway that We can use these custom geoip.dat and geosite.dat files for shadowsocks application?
thanks

**Comment by Loyalsoldier** [comment]
What platform/OS are you talking about?

**Comment by fsheidaiee** [comment]
> ~What platform/OS are you talking about?~
> 
> I just find out that Shadowsocks-windows supports custom geosite
> 
> [shadowsocks/shadowsocks-windows#3024](https://github.com/shadowsocks/shadowsocks-windows/issues/3024)

its all Chinese language and I don't understand anything

**Comment by Loyalsoldier** [comment]
https://github.com/shadowsocks/shadowsocks-windows/wiki/Experimental

**Comment by fsheidaiee** [comment]
> https://github.com/shadowsocks/shadowsocks-windows/wiki/Experimental

this is my config in v2ray:
},
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "127.0.0.0/8",
          "192.168.0.0/16",
          "geoip:ir"
        ]
      },
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all"
        ]
      }



How can I use this exactly in shadowsocks?

**Comment by Loyalsoldier** [comment]
AFAIK, Shadowsocks-windows doesn't support geoip and to block domains, so you can't achieve this.

**Comment by Loyalsoldier** [comment]
Now that you have achieved this in V2Ray, why do you need Shadowsocks anyway?

**Comment by fsheidaiee** [comment]
> Now that you have achieved this in V2Ray, why do you need Shadowsocks application?

Because of some bugs in udp connections in socks 5 and additional dns in v2rayng
