### ISSUE TITLE
建议单列国内CDN相关的域名

### ISSUE THREAD

**Issue by bososha** [Loyalsoldier/v2ray-rules-dat#6]
在DNS分流中，如果国内的域名全部使用DoH之类的加密DNS解析，会造成CDN相关（并不一定是CDN服务商的域名，所有解析的结果针对不同地区明显优化的域名都应归为此类）的域名通过远程的DNS服务器，解析到了DNS服务器所在地的IP地址。
例如，hdslb.com，bilivideo.com都属于此类域名，而bilibili.com不属于此类域名。

而诸如rubyfish，233py这类国内加密DNS提供商并没有在所有省份部署DNS服务器。

造成的结果是，使用上述加密DNS解析腾讯系qpic.cn, gtimg.cn等域名，和哔哩哔哩的bilivideo.com等域名，媒体访问体验均有明显下降甚至完全不可用。

个人使用的国内CDN域名列表基于以下仓库的数据，并添加了一些日常访问中遇到的其它国内CDN域名：
[https://github.com/mawenjian/china-cdn-domain-whitelist/blob/master/china-cdn-domain-whitelist.conf](url)

因此可否整理出较为完整的国内CDN域名列表，非常感谢！

**Comment by Loyalsoldier** [comment]
需要付出的精力太多，但收益甚微，所以暂时没有收集和整理大陆 CDN 域名的计划。如果你有意保持更新你的项目，我可以考虑引入你的项目中的大陆 CDN 域名，并在此项目中开一个专门的域名类别，譬如 `geosite:chinacdn`。

目前为止，个人觉得成本最小的方案还是：对于大陆域名，使用传统 DNS 解析。因为不管如何，在现阶段 EDNS 不普及的情况下，为了最终的地域解析准确性，最终还得使用传统 DNS 解析方案。既然必须用到传统 DNS 解析方案，那干脆所有大陆域名都使用传统 DNS 解析方案好了。

**Comment by bososha** [comment]
除了少数CDN域名以外，对多数域名的解析通过加密DNS进行保护，我认为有助于防止国内的DNS污染，以及有一定的隐私保护作用（不考虑SNI）。
目前我也在对日常的使用情况进行考虑，后期如果时机成熟，我打算直接PR至domain-list-community中，到时这边也可以直接fork。

谢谢！

**Comment by Loyalsoldier** [comment]
DNSPod 提供了 DOH 服务：https://doh.pub/dns-query
阿里 DNS 也提供了 DOH 服务：https://dns.alidns.com/dns-query

**Comment by bososha** [comment]
> DNSPod 提供了 DOH 服务：https://doh.pub/dns-query
> 阿里 DNS 也提供了 DOH 服务：https://dns.alidns.com/dns-query

感谢提醒！
