### ISSUE TITLE
广告屏蔽会让youtube app的观看历史记录功能失效

### ISSUE THREAD

**Issue by auslin45** [Loyalsoldier/v2ray-rules-dat#60]
前一阵子用了加强版的geosite，里面的广告屏蔽会让youtube app的观看历史记录功能失效，刚开始没想到是V2RAY的锅，找了半天才发现关掉geo资源文件里的广告屏蔽youtube历史记录就好用了，查了一下好像不能把*s.youtube.com屏蔽了，希望能处理一下

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/Loyalsoldier/v2ray-rules-dat/commit/3adea4962ea39944d41d0224fe24cb6def3cf769
