### ISSUE TITLE
建议将top域名移除direct-tld-list

### ISSUE THREAD

**Issue by EsuRt** [Loyalsoldier/v2ray-rules-dat#61]
国外有很多网站也使用top域名，导致访问非常慢，特别是一些视频服务，加载非常缓慢。经测试，将top域名加入代理后，加载速度较快。

**Comment by Loyalsoldier** [comment]
Fixed in https://github.com/Loyalsoldier/v2ray-rules-dat/commit/7dd299e63d6404d63ca438c0aac9d69940b39b78
