### ISSUE TITLE
希望添加gfwlist/gfwlist进geosite:gfw以便于路由模式的推广

### ISSUE THREAD

**Issue by SekiBetu** [Loyalsoldier/v2ray-rules-dat#62]
https://github.com/gfwlist/gfwlist
很多用户使用的以上的gfwlist，并且很多人不愿使用具有学习成本的路由模式
增加以上的规则进geosite:gfw并去重有助于PAC用户无缝切换到路由模式

**Comment by Loyalsoldier** [comment]
https://github.com/Loyalsoldier/v2ray-rules-dat/blob/0fae67f8858feb2ef9b2e7ab3e12339c429ac732/.github/workflows/run.yml#L148-L150

`geosite:gfw` 已包含 gfwlist 中的域名

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/103166990-40022300-481f-11eb-9dcb-c637284b6d10.png)
这边没有写明，希望写明，这样第一眼可以看到

**Comment by Loyalsoldier** [comment]
Done in https://github.com/Loyalsoldier/v2ray-rules-dat/commit/9486e7b460e11b4ca95e64921374ac948a2bfbb2
