### ISSUE TITLE
steam和steamcontent分离

### ISSUE THREAD

**Issue by Gabirel** [Loyalsoldier/v2ray-rules-dat#63]
你好，请问是否可以做到steam本身（steampowered.com）和steam在代理，但是国内的steamcontent可以在cn列表里

开了全局代理的路由模式后，发现steam下载内容仍然会去走代理（路由设置非cn都会走代理）。自己尝试调过很多次，但是似乎都无法正确地处理和解析

**Comment by Loyalsoldier** [comment]
用的什么客户端？

**Comment by Gabirel** [comment]
> 用的什么客户端？

`qv2ray 2.7.0-pre1:6039`

以及在v2rayN上都使用过～不过他们用都规则都是同一套

**Comment by Loyalsoldier** [comment]
首先，`steam` 的域名列表文件 [https://github.com/v2fly/domain-list-community/blob/master/data/steam](https://github.com/v2fly/domain-list-community/blob/master/data/steam) 不确保包含所有 steam 使用的域名。如果你的客户端配置为不进行 DNS 解析，访问不包含的 steam 域名的流量会直接走 V2Ray 第一个 outbound。

另外，`geosite:steam` 同时包含了大陆和海外的 steam 域名，不建议使用。

最后，建议直接使用 `geosite:cn`（不包含 steam 海外域名）

**Comment by Gabirel** [comment]
明白了这个关系了。谢谢！🙏

**Comment by Chow-Ray** [comment]
> 

您解决了吗？现在我还是遇到了这样的问题，steam下载走代理。
但是有时候走直连，有时候走代理
