### ISSUE TITLE
希望大佬解决一个小问题

### ISSUE THREAD

**Issue by 459696649** [Loyalsoldier/v2ray-rules-dat#64]
我在使用中发现一个小问题。。就是当你连接一个节点。有些网站比如虎牙，需要使用qq快速登录的时候，网站怎么刷新都不会出现快捷登录的QQ。直连和全部走代理都不会出现快捷登录的页面。 我也不会添加，求教大佬 希望下个直连方案里会解决这个小问题。每次要快捷登录QQ的时候 都需要手动断开节点连接。😒😒

**Comment by Loyalsoldier** [comment]
我都试过了，都正常。请检查自己的浏览器插件是不是误把某些网站的 QQ 快捷登录域名给屏蔽了。

**Comment by 459696649** [comment]
> 我都试过了，都正常。请检查自己的浏览器插件是不是误把某些网站的QQ快捷登录域名给屏蔽了。

我浏览器没有装任何插件。我前面都说的很详细了。我断开节点连接就可以了，明显是这些代理连接有问题啊。
