### ISSUE TITLE
geosite.dat里的广告域名能参考anti-AD项目吗

### ISSUE THREAD

**Issue by yeezylife** [Loyalsoldier/v2ray-rules-dat#65]
项目地址: https://github.com/privacy-protection-tools/anti-AD
命中率高不少,而且每天更新,也不用自己做整合了..adguardhome里中文的域名列表也是这个

**Comment by Loyalsoldier** [comment]
虽然与本项目 LICENSE 兼容，但是 privacy-protection-tools/anti-AD 项目违反了它所使用的其他项目的 LICENSE，所以本质上属于“侵权”项目，故不予采用。
