### ISSUE TITLE
前辈的Action脚本/Readme中的小问题

### ISSUE THREAD

**Issue by lychichem** [Loyalsoldier/v2ray-rules-dat#66]
![image](https://user-images.githubusercontent.com/9316590/104748911-2ce2d300-578d-11eb-8710-5d6df3b440ec.png)
Readme里提到要去整个secret，但是我刚才fork之后测试了一次，似乎不用secret也能跑起来，看了下脚本应该是直接下载了前辈release版的geolite?（现在我的fork已经暂时禁用action了不会给前辈造成压力）
emm感觉这个事吧如果有更多人钻空子可能会影响前辈的数据库访问权限，或者可能是前辈决定让我们使用您已经编译好的geolite但是readme忘改了？总之希望前者的事情不要发生吧，还是告知一下前辈~

**Comment by Loyalsoldier** [comment]
感谢提醒，确实不需要 secret，我忘记更新 README 了。
