### ISSUE TITLE
很想知道release中的文件怎么可以从raw.githubusercontent.com或cdn.xxx下载

### ISSUE THREAD

**Issue by xueshuaihang** [Loyalsoldier/v2ray-rules-dat#70]
geosite.dat：https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat

**Comment by Loyalsoldier** [comment]
打开上面链接，加载完毕后，右键另存为文件。

或者使用这个链接下载：https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

**Comment by xueshuaihang** [comment]
> 打开上面链接，加载完毕后，右键另存为文件。
> 
> 或者使用这个链接下载：https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

感激你的回答！但不好意思，我的意思是这个文件是怎么上传到raw.githubusercontent.com的，我用了相同的域名，后面替换了其他仓库release中的问题，就找不到

**Comment by Loyalsoldier** [comment]
https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat

上面这是 `release` 分支中的文件。通过 git push 发布到 release 分支。

https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

上面这是最新版本发布中的 asset。

**Comment by xueshuaihang** [comment]
> https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
> 
> 上面这是 `release` 分支中的文件。通过 git push 发布到 release 分支。
> 
> https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
> 
> 上面这是最新版本发布中的 asset。

感谢感谢，我懂了，最开始没发现这是分支，误以为是最新的`latast release`，原来还可以这样玩 👍
