### ISSUE TITLE
Block 添加 geosite:win-spy 后导致 Edge 浏览器无法同步

### ISSUE THREAD

**Issue by DustinWin** [Loyalsoldier/v2ray-rules-dat#71]
加入 Windows 操作系统相关的系统升级和隐私跟踪域名中的 Windows 操作系统使用的隐私跟踪域名（geosite:win-spy），添加入 Block 后，Edge 浏览器（版本：88.0.705.50）登录账号后进行同步，会显示一直同步中，且无法进行同步。
而在 Block 中移除“geosite:win-spy”后，可以正常同步。

**Comment by Loyalsoldier** [comment]
感谢提醒。可以帮忙看看日志，具体是哪个域名被屏蔽了导致问题出现吗？

**Comment by DustinWin** [comment]
> 感谢提醒。可以帮忙看看日志，具体是哪个域名被屏蔽了导致问题出现吗？

摘得日志如下：
127.0.0.1:11184 accepted //edge.activity.windows.com:443 [http -> block]
应该是这个地址：
edge.activity.windows.com
我测试了一下，的确是这个。

**Comment by Loyalsoldier** [comment]
感谢测试。

似乎上游也意识到这个问题，但并无修复的意愿：https://github.com/crazy-max/WindowsSpyBlocker/issues/205

**Comment by DustinWin** [comment]
> 感谢测试。
> 
> 似乎上游也已意识到这个问题，但并无修复的意愿：[crazy-max/WindowsSpyBlocker#205](https://github.com/crazy-max/WindowsSpyBlocker/issues/205)
> 
> 目前建议先自行将域名 `edge.activity.windows.com` 直连。

好的，谢谢。
