### ISSUE TITLE
geosite:gfw和geosite:greatfire是否包括geosite:telegram？

### ISSUE THREAD

**Issue by haomuch** [Loyalsoldier/v2ray-rules-dat#72]
如题，只代理geosite:gfw和geosite:greatfire，是否会包括geosite:telegram规则？另外telegram CIDR包含在哪个规则里面呢？

**Comment by Loyalsoldier** [comment]
可以自己验证：

https://github.com/v2fly/domain-list-community/blob/master/data/telegram

https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt

https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt

Telegram CIDR 是 IP 地址，不包含在 geosite 规则里。但是 README 里的「黑名单模式」列出的一大串 CIDR 就是 Telegram CIDR

**Comment by haomuch** [comment]
那能不能在geoip里加入一个telegram分类呢？

**Comment by Loyalsoldier** [comment]
Done https://github.com/Loyalsoldier/v2ray-rules-dat/commit/29deedd739184747754d07524a34540aff0a07cc
