### ISSUE TITLE
kh.google.com 无法访问

### ISSUE THREAD

**Issue by foxfun** [Loyalsoldier/v2ray-rules-dat#73]
kh.google.com 无法访问

**Comment by Loyalsoldier** [comment]
所以有啥问题？

**Comment by Loyalsoldier** [comment]
已修复。https://github.com/Loyalsoldier/v2ray-rules-dat/commit/235e8968c26bb1efbce25b66e65ca84d202c9ddb

抱歉，之前没理解你的意思。
