### ISSUE TITLE
按照windows的安装步骤使用scoop安装后怎么用呢？

### ISSUE THREAD

**Issue by SchumPeterC** [Loyalsoldier/v2ray-rules-dat#74]
Windows 用户可通过 Scoop 来安装：

scoop bucket add sushi https://github.com/kidonng/sushi
scoop install v2ray-rules-dat

按上面的步骤走了一遍，发现在C:\Users\用户名\scoop\apps\v2ray\4.34.0目录下有一个V2ray.exe文件，但是打开后是一个控制台窗口。
请问应该怎么使用?

**Comment by Loyalsoldier** [comment]
抱歉，之前没写明白。已更新使用说明，看最新 README。https://github.com/Loyalsoldier/v2ray-rules-dat/commit/080cc5f1bc7a2a71730052a35cdd06662d9112f0
