### ISSUE TITLE
proxy列表中有大量常用未屏蔽网站

### ISSUE THREAD

**Issue by haomuch** [Loyalsoldier/v2ray-rules-dat#78]
目前geolocation-!cn列表中有大量微软公司的未被屏蔽网站，比如microsoft.com，windows.com，office.com，bing.com，msn.com（为什么都跟微软过不去？）

已经在本人的fork中添加进proxy-need-to-remove.txt，请考虑尽快合并相关commit，并检查源文件的生成规则是否有问题，以致于引入了如此多正常网站。

**Comment by Loyalsoldier** [comment]
https://www.v2fly.org/config/routing.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E5%9F%9F%E5%90%8D%E5%88%97%E8%A1%A8

`geolocation-!cn`：包含了常见的非大陆站点域名，同时包含了 tld-!cn。

**Comment by haomuch** [comment]
> https://www.v2fly.org/config/routing.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E5%9F%9F%E5%90%8D%E5%88%97%E8%A1%A8
> 
> `geolocation-!cn`：包含了常见的非大陆站点域名，同时包含了 tld-!cn。

但是诸如微软的相关网站都在大陆能直接访问，而且很可能在大陆设有服务器，是否应该考虑将此类域名移出`geolocation-!cn`规则？否则生成的proxy-list.txt也名不副实。

或者是否可以考虑新建一个规则：`geosite:blacklist`，仅包含`geosite:gfw`和`geosite:greatfire`以及hidden分支中proxy.txt添加的域名，并且与proxy-list.txt文件关联，这样的黑名单规则可能更加准确实用。

**Comment by Loyalsoldier** [comment]
欢迎实现这个 https://github.com/felixonmars/dnsmasq-china-list/issues/341
