### ISSUE TITLE
教程写得很详细，可惜还是没看懂

### ISSUE THREAD

**Issue by Hinlavic** [Loyalsoldier/v2ray-rules-dat#79]
标题的层次是否有可以调整一下？
小白，好多地方的顺序都看不明白。

**Comment by Loyalsoldier** [comment]
😂 先搞懂 V2Ray 怎么用才来看这个。

https://www.v2fly.org
https://guide.v2fly.org

**Comment by Hinlavic** [comment]
还是用默认配置吧 学这个太费事了
