### ISSUE TITLE
中国谷歌框架DF-DFERH-01

### ISSUE THREAD

**Issue by 2398569839** [Loyalsoldier/v2ray-rules-dat#8]
可以尝试做一个不包含googleapis.cn的版本么
这会导致在中国使用谷歌商店会指向中国服务器
因为我使用的是v2ray_for_magisk版本
所以无法自己手动添加。您能帮我做一份么，谢谢
把googleapis.cn这个域去掉

**Comment by Loyalsoldier** [comment]
`googleapis.cn` 域名目前在代理域名列表里，而不是直连域名列表。在 `routing` 配置，代理域名走代理，直连域名直连，应该可以解决你的问题：

```
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": [
        "geosite:geolocation-!cn"
      ]
    },
    {
      "type": "field",
      "outboundTag": "Direct",
      "domain": [
        "geosite:cn"
      ]
    }
  ]
}
```

**Comment by 2398569839** [comment]
像这样的，如何改进
`  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        // Proxy DNS request
        "type": "field",
        "inboundTag": ["dns-in"],
        "outboundTag": "dns-out"
      },
      {
        // Bypass private IPs.
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "direct"
      },
      {
        // Bypass all china IPs.
        "type": "field",
        "ip": ["geoip:cn"],
        "outboundTag": "direct"
      },
      {
        // Bypass all china sites.
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      },
      {
        // Blocks major ads.
        "type": "field",
        "domain": ["geosite:category-ads"],
        "outboundTag": "blocked"
      },
      {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": ["geosite:geolocation-!cn"]
      },
      {
      "type": "field",
      "outboundTag": "Direct",
      "domain": ["geosite:cn"]
      },
    ]
  },`

**Comment by 2398569839** [comment]
其他我都整理好了，
这个routing部分不知道怎么搞改，单独弄出来

**Comment by 2398569839** [comment]
目前我的问题是，我使用代理时，会让链接定向到
googleapis.cn，这个怎么解决

**Comment by 2398569839** [comment]
经过简单搜索，出现"DF-DFERH-01"报错的根本原因是国行预置框架的商店启动时会向services.googleapis.cn获取数据，而正常情况下(国际版)是向services.googleapis.com获取的。
由于众所周知的原因，googleapis.cn指向了国内的服务器，不能提供完整的服务。

**Comment by 2398569839** [comment]
即使是挂了代理，谷歌商店也会定向至df-dferh-01

**Comment by Loyalsoldier** [comment]
```json
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    {
      "type": "field",
      "inboundTag": ["dns-in"],
      "outboundTag": "dns-out"
    },
    {
      "type": "field",
      "outboundTag": "blocked",
      "domain": ["geosite:category-ads"]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": ["geosite:geolocation-!cn"]
    },
    {
      "type": "field",
      "outboundTag": "direct",
      "domain": ["geosite:cn"]
    },
    {
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    },
    {
      "type": "field",
      "ip": ["geoip:cn"],
      "outboundTag": "direct"
    }
  ]
}
```

路由策略用 `IPIfNonMatch`，把关于 DNS 的路由规则放第一位，接着是禁止广告的，再接着是域名相关的，最后才是 IP 地址相关的。这样，代理列表中的域名，就会通过远程代理服务器进行 DNS 解析，也就不会被指向国内服务器了。

当然，前提是你所使用的 Android 客户端支持嗅探 DNS 解析域名。

**Comment by 2398569839** [comment]
这个是已经配置好了的么
可以直接用么，原谅我的无知

**Comment by Loyalsoldier** [comment]
```json
"routing": {
  "domainStrategy": "IPIfNonMatch",
  "rules": [
    //下面这个部分的DNS分流配置，请沿用你所用的android客户端的默认写法。记得删除这行说明文字
    {
      "type": "field",
      "inboundTag": ["dns-in"],
      "outboundTag": "dns-out"
    },
   //每个outboundTag的名称要对应outbounds里的tag。记得删除这行说明文字
    {
      "type": "field",
      "outboundTag": "blocked",
      "domain": ["geosite:category-ads"]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": ["geosite:geolocation-!cn"]
    },
    {
      "type": "field",
      "outboundTag": "direct",
      "domain": ["geosite:cn"]
    },
    {
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    },
    {
      "type": "field",
      "ip": ["geoip:cn"],
      "outboundTag": "direct"
    }
  ]
}
```

首先，Android 版 V2Ray 客户端不一定支持自定义配置，要先了解你所用的客户端是否支持；以及原本的配置 `routing` 里的 DNS 规则是怎么写的，要沿用默认配置。
其次，上面我写的那个是 `routing` 的配置，一是可能要改  DNS 的部分；二是每个 `outboundTag` 要对应 `outbounds` 里的每个 `tag`。

**Comment by 2398569839** [comment]
我是在安卓上使用的
但准确说的说，我用的并不是客户端
我是通过magisk嵌入模块进andriod系统中来达到使用v2ray的问题
我看了配置，用的依然是v2ray的内核

**Comment by 2398569839** [comment]
我给你发个config.json你看一下

**Comment by 2398569839** [comment]
[config.json.txt](https://github.com/Loyalsoldier/v2ray-rules-dat/files/4270080/config.json.txt)
不改成 后缀txt就无法上传

**Comment by Loyalsoldier** [comment]
你遇到的这个问题，是因为 `googleapis.cn` 这个域名被本地 DNS 解析成国内 IP 地址了，所以被分流到国内谷歌服务器。要解决这个问题，两个方式：

- 把这个域名写在 dat 规则文件的 `geolocation-!cn` 类别里，然后把这个类别的域名转发到远程服务器
- 通过代理服务器来访问国外的 DNS 解析服务器（如 `1.1.1.1`），从而得到这个域名的国外 IP 地址

搞懂下面这几项，剩下的自行研究：

1. 看懂 DNS 配置
2. 搞懂 V2Ray 不同 `Protocol` 的作用
3. 搞懂 `IPIfNonMatch` 和 `IPOnDemand` 两种路由分流策略的区别
4. V2Ray JSON 配置中，越在配置文件上方的规则，优先级越高

**Comment by 2398569839** [comment]
可以给个联系方式么，我想试着学习解决
但是我懂的并不多

**Comment by 2398569839** [comment]
第一个问题的话可以给个编译dat的工具么

**Comment by Loyalsoldier** [comment]
本项目的 dat 规则文件没问题，重点是不同的 V2Ray 配置会产生不同的结果，要知道怎么配置成你要的方式。我使用的针对命令行 V2Ray 客户端的配置文件看项目 README.md 文档最后一部分。基础的原理部分，请参考 V2Ray 官网。

**Comment by IceCodeNew** [comment]
> 经过简单搜索，出现"DF-DFERH-01"报错的根本原因是国行预置框架的商店启动时会向services.googleapis.cn获取数据，而正常情况下(国际版)是向services.googleapis.com获取的。
> 由于众所周知的原因，googleapis.cn指向了国内的服务器，不能提供完整的服务。

```
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [{
        "address": "https+local://dns.alidns.com/dns-query",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      "https://1.0.0.1/dns-query",
      "localhost"
    ]
  },
```

**Comment by IceCodeNew** [comment]
> > 经过简单搜索，出现"DF-DFERH-01"报错的根本原因是国行预置框架的商店启动时会向services.googleapis.cn获取数据，而正常情况下(国际版)是向services.googleapis.com获取的。
> > 由于众所周知的原因，googleapis.cn指向了国内的服务器，不能提供完整的服务。
> 
> ```json
>   "dns": {
>     "hosts": {
>       "domain:googleapis.cn": "googleapis.com"
>     },
>     "servers": [{
>         "address": "https+local://dns.alidns.com/dns-query",
>         "domains": [
>           "geosite:cn"
>         ],
>         "expectIPs": [
>           "geoip:cn"
>         ]
>       },
>       "https://1.0.0.1/dns-query",
>       "localhost"
>     ]
>   },
> ```

还需要配合路由规则：
```json
  "routing": {
    "domainStratedy": "IPIfNonMatch",
    "rules": [{
      "type": "field",
      "domain": [
        "geosite:google"
      ],
      "outboundTag": "proxy"
    },{
      "type": "field",
      "domain": [
        "geosite:cn"
      ],
      "outboundTag": "direct"
    },{
      "type": "field",
      "ip": [
        "geoip:private",
        "geoip:cn"
      ],
      "outboundTag": "direct"
    }]
  },
```
