### ISSUE TITLE
推荐去广告源

### ISSUE THREAD

**Issue by liuluping0106** [Loyalsoldier/v2ray-rules-dat#80]
推荐一个很不错的去广告整合源：https://github.com/privacy-protection-tools/anti-AD

**Comment by liuluping0106** [comment]
希望可以实现自动更新，添加一个可以订阅的东西？

**Comment by Loyalsoldier** [comment]
> 推荐一个很不错的去广告整合源：https://github.com/privacy-protection-tools/anti-AD

https://github.com/Loyalsoldier/v2ray-rules-dat/issues/65#issuecomment-757805664

**Comment by Loyalsoldier** [comment]
> 希望可以实现自动更新，添加一个可以订阅的东西？

https://github.com/Loyalsoldier/v2ray-rules-dat/issues/10
