### ISSUE TITLE
Workflow 似乎应当针对 v2fly/domain-list-community 的更新做些修改？

### ISSUE THREAD

**Issue by IceCodeNew** [Loyalsoldier/v2ray-rules-dat#81]
如题，参见 https://github.com/v2fly/domain-list-community/commit/36f0a37aeafa57d170c7baa2a6eb58b9420b5903

**Comment by Loyalsoldier** [comment]
并不影响，因为这个项目生成 `geosite.dat` 使用的是 https://github.com/Loyalsoldier/domain-list-custom

**Comment by Loyalsoldier** [comment]
BTW，还是修了个小 bug https://github.com/Loyalsoldier/v2ray-rules-dat/commit/036184df55bf27b5933c1d6b3c9114a374958e95
