### ISSUE TITLE
建议在 geosite:gfw 中移除 store.steampowered.com 项

### ISSUE THREAD

**Issue by spraysparks** [Loyalsoldier/v2ray-rules-dat#82]
目前在多个地区测试 store.steampowered.com 以及 steamcdn-*.akamaihd.net 没有被墙，希望可以在 geosite:gfw 中移除这些域名。

**Comment by Loyalsoldier** [comment]
`geosite:gfw` 项是获取的 GFWList 的域名数据，目前暂时不打算自行增删。另外，Greatfire 上检测到依然被屏蔽 https://zh.greatfire.org/store.steampowered.com

建议你自行添加到直连列表。
