### ISSUE TITLE
你好不懂程序代码的想来问问

### ISSUE THREAD

**Issue by YuanBo1996** [Loyalsoldier/v2ray-rules-dat#86]
在v2rayN更新V4.12后，在PAC[Do not change system proxy]模式下，无法打开google和YouTube，只能全局模式才能打开被墙的网站。
我按照使用方式，从“Released on 202103032209”里下载了“geoip.dat”和“geosite.dat”
也放入了v2rayN的客户端文件夹下覆盖，并按照简介里说的，复制黏贴了“Routing 配置方式”，“白、黑名单模式 Routing 配置方式”，在settings，Routingsetting点下OK后，不但PAC模式依然失效，全局代理也崩了。我现在应该怎么“修好”这个？

**Comment by Loyalsoldier** [comment]
首先，这个项目的示例配置只适用于 V2Ray 命令行客户端（也就是从这里下载的 v2ray https://github.com/v2fly/v2ray-core/releases ），其他带有图形界面的客户端（例如 v2rayN 和 Qv2ray）不能直接复制粘贴示例配置来使用。

其次，我不是 Windows 用户，也不是 v2rayN 用户，没法帮到你。建议到 https://github.com/2dust/v2rayN/issues 提问。

最后，我看了你的描述，建议你看看 v2rayN 的[官方教程](https://github.com/2dust/v2rayN/wiki/%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86%E5%92%8C%E8%B7%AF%E7%94%B1)。
