### ISSUE TITLE
geo资源文件和自定义规则哪一个在起作用？

### ISSUE THREAD

**Issue by aplixy** [Loyalsoldier/v2ray-rules-dat#87]
![IMG_20210306_061850](https://user-images.githubusercontent.com/5989299/110180004-0283cc80-7e44-11eb-8a03-80a7070224a2.jpg)
![IMG_20210306_061918](https://user-images.githubusercontent.com/5989299/110180023-07e11700-7e44-11eb-91e3-60bf3e87f0da.jpg)

现在Android新版v2rayNG也支持添加geo资源文件了，但是同时也支持添加自定义规则，请问这两个是否冲突？具体是哪一个在起作用？

**Comment by Loyalsoldier** [comment]
请到 https://github.com/2dust/v2rayNG/issues 提 issue。
