### ISSUE TITLE
QQ快速登录问题

### ISSUE THREAD

**Issue by snhun** [Loyalsoldier/v2ray-rules-dat#90]
开黑名单，PC端TIM的快速登录会无效，查看了下qq相关的域名都是直连的。关掉系统代理正常！
![QQ截图20210314102018.png](https://i.loli.net/2021/03/14/GcYxC682ykslWa1.png)
![QQ截图20210314102128.png](https://i.loli.net/2021/03/14/FRf1qIuOjSJNHl2.png)

**Comment by Loyalsoldier** [comment]
去掉广告屏蔽试一试。

**Comment by snhun** [comment]
> 去掉广告屏蔽试一试。

不对哦，还是这样

**Comment by Loyalsoldier** [comment]
可以试试 `freedom` outbound 的 `domainStrategy` 用 `AsIs`，不要用 `UseIP` 相关的。

**Comment by snhun** [comment]
还是无法关联PC快捷登录，订阅的黑名单规则是
https://raw.githubusercontent.com/2dust/v2rayCustomRoutingList/master/custom_routing_rules_blacklist

**Comment by Loyalsoldier** [comment]
也许 QQ 快速安全登录能检测请求是否由代理软件发出。如果是这样的话，暂时无解。

**Comment by snhun** [comment]
了解，那只能使用时手动关了。多谢耐心解答呀！
