### ISSUE TITLE
建议将hostloc.com从geosite:cn删除

### ISSUE THREAD

**Issue by XMD0718** [Loyalsoldier/v2ray-rules-dat#91]
geosite:cn类别通常用于直连，而hostloc.com目前在国内存在被阻断现象，尤其是移动，请删除

**Comment by Loyalsoldier** [comment]
Done in https://github.com/Loyalsoldier/v2ray-rules-dat/commit/8bb37b5b03a1168077f8adb22b33db0bc314db86
