### ISSUE TITLE
可否提供一个标签关键词的说明？

### ISSUE THREAD

**Issue by somelee** [Loyalsoldier/v2ray-rules-dat#93]
例如：
geosite:cn,
geosite:apple-cn

很多标签都是查看例子才知道，但是似乎这个项目还提供很多其他标签，例如：adobe-activation等。

如何才能得知项目中都有那些标签，并且这些标签的覆盖范围？

**Comment by Loyalsoldier** [comment]
本项目是项目 [v2fly/domain-list-community](https://github.com/v2fly/domain-list-community) 的扩展。

除了本项目特有的类别(标签)外，其余所有类别都可以在 `v2fly/domain-list-community` 项目的 [data](https://github.com/v2fly/domain-list-community/tree/master/data) 目录中找到，类别名为 `geosite:文件名`
