### ISSUE TITLE
没有屏蔽需要到一定年龄才能使用的网站的功能

### ISSUE THREAD

**Issue by htmlrust** [Loyalsoldier/v2ray-rules-dat#96]
`geosite:age18+`

需要屏蔽年龄在18岁以上才能使用的网站。 

`geosite:age18+-sex`
色情网站
`geosite:age18+-其它需要成年人访问的网站`
其它还没想好，18岁以上访问的网址。

**Comment by Loyalsoldier** [comment]
请直接使用带有家长控制功能的 DNS。
